---
sidebar: sidebar
permalink: concept-overview.html
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers
summary: NetApp BlueXP provides your organization with a single control plane that helps you build, protect, and govern data across your on-premises and cloud environments. The BlueXP SaaS platform includes services that provide storage management, data mobility, data protection, and data analysis and control. Management capabilities are provided through a web-based console and APIs.
---

= Learn about BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp BlueXP provides your organization with a single control plane that helps you build, protect, and govern data across your on-premises and cloud environments. The BlueXP software as a service (SaaS) platform includes services that provide storage management, data mobility, data protection, and data analysis and control. Management capabilities are provided through a web-based console and APIs.

== Features

BlueXP provides unified control of storage and data services across your hybrid multicloud.

=== Unified control of storage from the BlueXP canvas

The _BlueXP canvas_ enables you to discover, deploy, optimize, and manage cloud and on-premises storage. The canvas provides a single location for all storage management.

==== Supported cloud and on-premises storage

Cloud storage solutions::
* Amazon FSx for NetApp ONTAP
* Azure NetApp Files
* Cloud Volumes ONTAP

On-premises flash and object storage::
* E-Series systems
* ONTAP clusters
* StorageGRID systems

Cloud object storage::
* Amazon S3 storage
* Azure Blob storage
* Google Cloud Storage

==== Working environments

When you discover or deploy cloud or on-premises storage from BlueXP, you create a _working environment_ on the BlueXP canvas. To manage your cloud or on-premises storage, you select a working environment and then either integrate it with BlueXP data services or enter the working environment to complete storage management actions like adding volumes.

=== Integrated services to protect, secure, and optimize data

BlueXP includes a comprehensive suite of integrated data services to help you maintain the security, integrity, and availability of your data across your on-premises and cloud storage environments.

BlueXP alerts::
View issues related to capacity, availability, performance, protection, and security in your ONTAP environment.

BlueXP automation catalog::
Use scripted solutions to automate the deployment and integration of NetApp products and services.

BlueXP backup and recovery::
Back up and restore cloud and on-prem data.

BlueXP classification::
Get your application data and cloud environments privacy ready.

BlueXP cloud ops::
Gain visibility into your cloud compute spending and identify potential savings.

BlueXP copy and sync::
Sync data between on-prem and cloud data stores.

BlueXP digital advisor::
Use predictive analytics and proactive support to optimize your data infrastructure.

BlueXP digital wallet::
Manage and monitor your licenses and subscriptions.

BlueXP disaster recovery::
Protect on-premises VMware workloads using VMware Cloud on Amazon FSx for ONTAP as a disaster recovery site.

BlueXP economic efficiency::
Identify clusters with current or forecasted low capacity and implement data tiering or additional capacity recommendations.

BlueXP operational resiliency::
Implement automated firmware and software configuration risk remediations to maintain the health of ONTAP clusters.

BlueXP ransomware protection::
Detect anomalies that might result in ransomware attacks. Protect and recover workloads.

BlueXP replication::
Replicate data between storage systems to support backup and disaster recovery.

BlueXP software updates::
Automate the assessment, planning, and execution of ONTAP upgrades.

BlueXP sustainability dashboard::
Analyze the sustainability of your storage systems.

BlueXP tiering::
Extend your on-prem ONTAP storage to the cloud.

BlueXP volume caching::
Create a writable cache volume to speed up access to data or offload traffic from heavily accessed volumes.

BlueXP workload factory::
Design, set up, and operate key workloads using Amazon FSx for NetApp ONTAP.

https://www.netapp.com/bluexp/[Learn more about BlueXP and the available data services^]

=== Integrated services to protect, secure, and optimize data

BlueXP includes a comprehensive suite of integrated data services to help you maintain the security, integrity, and availability of your data across your on-premises and cloud storage environments.

* *BlueXP alerts*: View issues related to capacity, availability, performance, protection, and security in your ONTAP environment.

* *BlueXP automation catalog*: Use scripted solutions to automate the deployment and integration of NetApp products and services.

* *BlueXP backup and recovery*: Back up and restore cloud and on-prem data.

* *BlueXP classification*: Get your application data and cloud environments privacy ready.

* *BlueXP cloud ops*: Gain visibility into your cloud compute spending and identify potential savings.

* *BlueXP copy and sync*: Sync data between on-prem and cloud data stores.

* *BlueXP digital advisor*: Use predictive analytics and proactive support to optimize your data infrastructure.

* *BlueXP digital wallet*: Manage and monitor your licenses and subscriptions.

* *BlueXP disaster recovery*: Protect on-premises VMware workloads using VMware Cloud on Amazon FSx for ONTAP as a disaster recovery site.

* *BlueXP economic efficiency*: Identify clusters with current or forecasted low capacity and implement data tiering or additional capacity recommendations.

* *BlueXP operational resiliency*: Implement automated firmware and software configuration risk remediations to maintain the health of ONTAP clusters.

* *BlueXP ransomware protection*: Detect anomalies that might result in ransomware attacks. Protect and recover workloads.

* *BlueXP replication*: Replicate data between storage systems to support backup and disaster recovery.

* *BlueXP software updates*: Automate the assessment, planning, and execution of ONTAP upgrades.

* *BlueXP sustainability dashboard*: Analyze the sustainability of your storage systems.

* *BlueXP tiering*: Extend your on-prem ONTAP storage to the cloud.

* *BlueXP volume caching*: Create a writable cache volume to speed up access to data or offload traffic from heavily accessed volumes.

* *BlueXP workload factory*: Design, set up, and operate key workloads using Amazon FSx for NetApp ONTAP.

https://www.netapp.com/bluexp/[Learn more about BlueXP and the available data services^]

=== Integrated services to protect, secure, and optimize data

BlueXP includes a comprehensive suite of integrated data services to help you maintain the security, integrity, and availability of your data across your on-premises and cloud storage environments.

[horizontal]
BlueXP alerts::
View issues related to capacity, availability, performance, protection, and security in your ONTAP environment.

BlueXP automation catalog::
Use scripted solutions to automate the deployment and integration of NetApp products and services.

BlueXP backup and recovery::
Back up and restore cloud and on-prem data.

BlueXP classification::
Get your application data and cloud environments privacy ready.

BlueXP cloud ops::
Gain visibility into your cloud compute spending and identify potential savings.

BlueXP copy and sync::
Sync data between on-prem and cloud data stores.

BlueXP digital advisor::
Use predictive analytics and proactive support to optimize your data infrastructure.

BlueXP digital wallet::
Manage and monitor your licenses and subscriptions.

BlueXP disaster recovery::
Protect on-premises VMware workloads using VMware Cloud on Amazon FSx for ONTAP as a disaster recovery site.

BlueXP economic efficiency::
Identify clusters with current or forecasted low capacity and implement data tiering or additional capacity recommendations.

BlueXP operational resiliency::
Implement automated firmware and software configuration risk remediations to maintain the health of ONTAP clusters.

BlueXP ransomware protection::
Detect anomalies that might result in ransomware attacks. Protect and recover workloads.

BlueXP replication::
Replicate data between storage systems to support backup and disaster recovery.

BlueXP software updates::
Automate the assessment, planning, and execution of ONTAP upgrades.

BlueXP sustainability dashboard::
Analyze the sustainability of your storage systems.

BlueXP tiering::
Extend your on-prem ONTAP storage to the cloud.

BlueXP volume caching::
Create a writable cache volume to speed up access to data or offload traffic from heavily accessed volumes.

BlueXP workload factory::
Design, set up, and operate key workloads using Amazon FSx for NetApp ONTAP.

https://www.netapp.com/bluexp/[Learn more about BlueXP and the available data services^]

== Supported cloud providers

BlueXP enables you to manage cloud storage and use cloud services in Amazon Web Services, Microsoft Azure, and Google Cloud.

== Cost

Pricing for BlueXP depends on the services that you plan to use. https://bluexp.netapp.com/pricing[Learn about BlueXP pricing^]

== How BlueXP works

BlueXP includes a web-based console that's provided through the SaaS layer, a resource and access management system, Connectors that manage working environments and enable BlueXP cloud services, and different deployment modes to meet your business requirements.

=== Software-as-a-service

BlueXP is accessible through a https://console.bluexp.netapp.com[web-based console^] and APIs. This SaaS experience enables you to automatically access the latest features as they're released and to easily switch between your BlueXP organizations, projects, and Connectors.

=== BlueXP identity and access management (IAM)

BlueXP identity and access management (IAM) is a resource and access management model that provides granular management of resources and permissions:

* A top-level _organization_ enables you to manage access across your various _projects_
* _Folders_ enable you to group related projects together
* Resource management enables you to associate a resource with one or more folders or projects
* Access management enables you to assign a role to members at different levels of the organization hierarchy

BlueXP IAM is supported when using BlueXP in standard mode. If you're using BlueXP in restricted mode or private mode, then you'll use a BlueXP _account_ to manage workspaces, users, and resources.

* link:concept-identity-and-access-management.html[Learn more about BlueXP IAM]
* link:concept-netapp-accounts.html[Learn about BlueXP accounts]

=== Connectors

You don't need a Connector to get started with BlueXP, but you'll need to create a Connector to unlock all BlueXP features and services. A Connector enables the management of resources and processes across your on-premises and cloud environments. It's required to manage working environments (for example, Cloud Volumes ONTAP) and to use many BlueXP services.

link:concept-connectors.html[Learn more about Connectors].

=== Deployment modes

BlueXP offers three deployment modes. _Standard mode_ leverages the BlueXP software as a service (SaaS) layer to provide full functionality. If your environment has security and connectivity restrictions, _restricted mode_ and _private mode_ limit outbound connectivity to the BlueXP SaaS layer.

link:concept-modes.html[Learn more about BlueXP deployment modes].

== SOC 2 Type 2 certification

An independent certified public accountant firm and services auditor examined BlueXP and affirmed that it achieved SOC 2 Type 2 reports based on the applicable Trust Services criteria.

https://www.netapp.com/company/trust-center/compliance/soc-2/[View NetApp's SOC 2 reports^]