---
sidebar: sidebar
permalink: concept-overview.html
keywords: overview, concepts, features, use case, cloud manager, bluexp, how bluexp works, supported cloud providers, cloud providers, hyperscalers
summary: NetApp BlueXP provides your organization with a single control plane that helps you build, protect, and govern data across your on-premises and cloud environments. The BlueXP SaaS platform includes services that provide storage management, data mobility, data protection, and data analysis and control. Management capabilities are provided through a web-based console and APIs.
---

= Learn about BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp BlueXP provides your organization with a single control plane that helps you build, protect, and govern data across your on-premises and cloud environments. The BlueXP SaaS platform includes services that provide storage management, data mobility, data protection, and data analysis and control. Management capabilities are provided through a web-based console and APIs.

== Features

The BlueXP platform provides four main pillars of data management: storage, mobility, protection, and analysis and control.

Storage:: 
Discover, deploy, and manage storage, whether it's in AWS, Azure, Google Cloud, or on premises.

* Set up and use cloud file-storage services:
+
** https://bluexp.netapp.com/azure-netapp-files[Azure NetApp Files^]
** https://bluexp.netapp.com/fsx-for-ontap[Amazon FSx for NetApp ONTAP^]
** https://bluexp.netapp.com/cloud-volumes-service-for-gcp[Cloud Volumes Service for Google Cloud^]

* Set up and use https://bluexp.netapp.com/ontap-cloud[Cloud Volumes ONTAP^] for efficient, multi-protocol data management across clouds.

* Discover and manage https://bluexp.netapp.com/netapp-on-premises[on-premises storage^]:
** E-Series systems
** ONTAP clusters
** StorageGRID systems

Mobility::
Move data where it's needed by syncing, copying, tiering, and caching data.

** https://bluexp.netapp.com/cloud-sync-service[Copy and sync^]
** https://bluexp.netapp.com/cloud-tiering[Tiering^]

Protection::
Use automated protection mechanisms to protect data against data loss, unplanned outages, ransomware, and other cyber threats.

** https://bluexp.netapp.com/cloud-backup[Backup and recovery^]
** https://bluexp.netapp.com/disaster-recovery[Disaster recovery^]
** https://bluexp.netapp.com/replication[Replication^]
** https://bluexp.netapp.com/ransomware-protection[Ransomware protection^]

Analysis and control::
Use tools to monitor, map, and optimize your data storage and infrastructure. Gain actionable intelligence to optimize storage health, resiliency, and economics.

** https://bluexp.netapp.com/netapp-cloud-data-sense[Classification^]
** https://bluexp.netapp.com/digital-advisor[Digital advisor^]
** https://bluexp.netapp.com/digital-advisor[Economic efficiency^]
** https://bluexp.netapp.com/digital-advisor[Operational resiliency^]

https://bluexp.netapp.com/[Learn more about how you can use BlueXP to help your organization^]

== Supported cloud providers

BlueXP enables you to manage cloud storage and use cloud services in Amazon Web Services, Microsoft Azure, and Google Cloud.

== Cost

Pricing for BlueXP depends on the services that you plan to use. https://bluexp.netapp.com/pricing[Learn about BlueXP pricing^]

== How BlueXP works

BlueXP includes a web-based console that's provided through the SaaS layer, a resource and access management system, and Connectors that manage working environments and enable BlueXP cloud services.

=== Software-as-a-service

BlueXP is accessible through a https://console.bluexp.netapp.com[web-based console^] and APIs. This SaaS experience enables you to automatically access the latest features as they're released and to easily switch between your BlueXP organizations, projects, and Connectors.

=== BlueXP identity and access management (IAM)

BlueXP identity and access management (IAM) is a resource and access management model that provides granular management of resources and permissions:

* A top-level _organization_ enables you to manage access across your various _projects_
* _Folders_ enable you to group related projects together
* Resource management enables you to associate a resource with one or more folders or projects
* Access management enables you to assign a role to members at different levels of the organization hierarchy

BlueXP IAM is supported when using BlueXP in standard mode. If you're using BlueXP in restricted mode or private mode, then you'll use a BlueXP _account_ to manage workspaces, users, and resources.

* link:concept-identity-and-access-management.html[Learn more about BlueXP IAM].
* link:concept-netapp-accounts.html[Learn about BlueXP accounts].

=== Connectors

You don't need a Connector to get started with BlueXP, but you'll need to create a Connector to unlock all BlueXP features and services. A Connector enables the management of resources and processes across your on-premises and cloud environments. It's required to manage working environments (for example, Cloud Volumes ONTAP and on-premises ONTAP clusters) and to use many BlueXP data services.

link:concept-connectors.html[Learn more about Connectors].

=== Deployment modes 

BlueXP is supported in environments that have security and connectivity restrictions. You can use _restricted mode_ or _private mode_ to limit outbound connectivity to the BlueXP SaaS layer.

link:concept-modes.html[Learn more about BlueXP deployment modes].

== SOC 2 Type 2 certification

An independent certified public accountant firm and services auditor examined BlueXP and affirmed that it achieved SOC 2 Type 2 reports based on the applicable Trust Services criteria.

https://www.netapp.com/company/trust-center/compliance/soc-2/[View NetApp's SOC 2 reports^]
