---
sidebar: sidebar
permalink: concept-data-services.html
keywords: concept, connectors, learn about connectors, what are connectors, what is a connector, what's a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery
summary: A Connector is NetApp software running in your cloud network or on-premises network. It executes the actions that BlueXP needs to perform in order to manage your data infrastructure. The Connector constantly polls the BlueXP SaaS layer for any actions that it needs to take. You don't need a Connector to get started with BlueXP, but you'll need to create a Connector to unlock all BlueXP features and services.
---

= Learn about BlueXP services
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp BlueXP provides your organization with a single control plane that helps you build, protect, and govern data across your on-premises and cloud environments. 

You can choose whether to use BlueXP SaaS service (standard mode), run BlueXP in your restricted cloud environment (restricted mode), or install it within your own on-premises data center (private mode). Whatever your environment, you can take advantage of centralized management and additional data services that keep your storage resources healthy and safeguarded.

The mode you choose determines which services are available to you and what storage resources you can manage. 

Before you get started, compare the different storage resources each mode supports along with available data services to help you decide which makes sense for your company's needs.

== Data services

The following table indicates which data services are available in each deployment mode, whether you need a subscription and when you need a support account.

[NOTE]
=====
*Connectors*
The Connector column in the table indicates when you need to have a Connector for standard mode. You always need to have a Connector if you use BlueXP in restricted mode or private mode.
=====

[cols=5*,options="header",cols="24,19,19,19,19"]
|===

| 
| Requires support account
| Requires Connector
| Requires subscription
| Mode availability


| Alerts | Yes | Yes | No | All

| Backup and recovery |	Yes | Yes | Yes | Standard, Restricted

| Classification | Yes | No | No | All

| Copy and sync| No | No | Yes |

| Digital advisor | Yes | No | No  | All

| Digital wallet  | Yes | No* | No | All

| Disaster recovery  | No | Yes | Yes | Standard, Restricted

| Economic efficiency  | Yes | Yes | No | 

| Operational resiliency  | Yes | Yes* | No |

| Ransomware protection  | No | Yes | No | Standard
| Replication | No| No* | No | Standard, Restricted

| Software updates | Yes | No | No | All

| Support case management | Yes | No | No | All

| Tiering | No | No* | Yes | Standard

| Volume caching | No | No | No | Standard

| Workloads |  |  |

|===


== NetApp storage

You can manage most of your NetApp storage resources directly from BlueXP, allowing you to view all of your resources from the same application. 

The following table lists which storage resources you can manage from each deployment mode, as well if you need a Connector or a subscription.

[NOTE]
=====
*Connectors*
The Connector column in the table indicates when you need to have a Connector for standard mode. You always need to have a Connector if you use BlueXP in restricted mode or private mode.
=====

 



[cols=5*,options="header",cols="24,19,19,19,19"]
|===

| 
| Requires support account
| Requires Connector
| Requires subscription
| Mode availability



| Amazon FSx for NetApp ONTAP | Yes | No^1^ | Yes | Standard

| Amazon S3 storage |	Yes | No | Yes | Standard

| Azure Blob storage | Yes | No | No | Standard

| Azure NetApp Files | No | No^2^ | Yes | Standard, Restricted

| Cloud Volumes ONTAP | Yes | Yes | Yes | Standard, Restricted

| Cloud Volumes Service for Google Cloud | No | No | Yes? | Standard

| E-Series systems | No | Yes | No | Standard

| Google Cloud Storage | No | Yes | Yes? | Standard

| On-premises ONTAP clusters  | Yes | No^3^ | No  | All

| StorageGRID | Yes | Yes | No  | Standard, Restricted

|===

^1^ Some actions require a Connector or a BlueXP workload factory link. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html[Learn which actions require a Connector or link^]

^2^ While a Connector isn't required to set up and manage Azure NetApp Files, a Connector is required if you want to use BlueXP classification to scan Azure NetApp Files data.

^3^ While a Connector isn't required for direct discovery of an on-premises ONTAP cluster, a Connector is required if you want to take advantage of additional BlueXP features. https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Learn more about discovery and management options for on-prem ONTAP clusters^]



