---
sidebar: sidebar
permalink: concept-connectors.html
keywords: concept, connectors, learn about connectors, what are connectors, what is a connector, what's a connector, days, 14 days, when is a connector required, connector supported locations, restricted mode, private mode, dark site, permissions, multiple connectors, disaster recovery, agent
summary: A Connector is NetApp software running in your cloud network or on-premises network. It executes the actions that BlueXP needs to perform in order to manage your data infrastructure. The Connector constantly polls the BlueXP SaaS layer for any actions that it needs to take. You don't need a Connector to get started with BlueXP, but you'll need to create a Connector to unlock all BlueXP features and services.
---

= Learn about Connectors
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
include::_include/connector-definition.adoc[]

If you run BlueXP in standard mode, you won't need to install a Connector to run some of BlueXP's services, such as software updates and digital wallet. However, some of BlueXP's premium services such as ransomware protection or disaster recovery require that you install a Connector. If you use BlueXP in restricted or private mode, you'll need to install a Connector.

== What you can do without a Connector in standard mode

Some of BlueXP's most important services are available without installing a Connector if you are running in standard mode. 

You can use the following BlueXP features and services without a Connector:

* Amazon FSx for NetApp ONTAP
+
Some actions require a Connector or a BlueXP workload factory link. https://docs.netapp.com/us-en/bluexp-fsx-ontap/start/concept-fsx-aws.html[Learn which actions require a Connector or link^]

* Automation catalog

* Azure NetApp Files
+
While a Connector isn't required to set up and manage Azure NetApp Files, a Connector is required if you want to use BlueXP classification to scan Azure NetApp Files data.

* Cloud Volumes Service for Google Cloud

* Copy and sync

* Digital advisor

* Digital wallet (licenses only, subscription monitoring requires a Connector)
+
In almost all cases, you can add a license to the digital wallet without a Connector.
+
The only time that a Connector is required to add a license to the digital wallet is for Cloud Volumes ONTAP _node-based_ licenses. A Connector is required because BlueXP needs to reach the license data installed on your Cloud Volumes ONTAP systems.

* Direct discovery of on-premises ONTAP clusters
+
While a Connector isn't required for direct discovery of an on-premises ONTAP cluster, a Connector is required if you want to take advantage of additional BlueXP features. 
+
https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Learn more about discovery and management options for on-prem ONTAP clusters^]

* Software updates

* Sustainability

* Workload factory

== When a Connector is required

When you use BlueXP in standard mode, you'll need to install one or more Connectors to enable the following features and services in BlueXP:

* Alerts
* Amazon FSx for ONTAP management features
* Amazon S3 storage
* Azure Blob storage
* Backup and recovery
* Classification
* Cloud Volumes ONTAP
* Disaster recovery
* E-Series systems
* Economic efficiency (view-only)
* Google Cloud Storage buckets
* On-premises ONTAP cluster integration with BlueXP data services
* Operational resiliency (view-only)
* Ransomware protection
* StorageGRID systems
* Tiering
* Volume caching



== Connectors must be operational at all times

Because Connectors are a fundamental part of the BlueXP service architecture, you need to ensure that your relevant Connectors are up, operational, and accessible at all times. While the service is designed to overcome short outages of Connector availability, you must take immediate action when required to remedy infrastructure failures.

This documentation is governed by the EULA. If the product is not operated in accordance with the documentation, the functionality and operation of the product, as well as your rights under the EULA, may be adversely impacted.

=== Impact on Cloud Volumes ONTAP

A Connector is a key component in the health and operation of Cloud Volumes ONTAP. If a Connector is powered down, Cloud Volumes ONTAP PAYGO systems and capacity-based BYOL systems shut down after losing communication with a Connector for longer than 14 days. This happens because the Connector refreshes licensing on the system each day.

If your Cloud Volumes ONTAP system has a node-based BYOL license, the system remains running after 14 days because the license is installed on the Cloud Volumes ONTAP system.

== Supported locations

You can install Connectors in a supported hyperscaler environment, or on your premises, depending on your needs.

* Amazon Web Services

* Microsoft Azure
+
Deploy your Connector in the same Azure region as the Cloud Volumes ONTAP systems that it manages, or in the https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies[Azure region pair^] for the Cloud Volumes ONTAP systems. This ensures that an Azure Private Link connection is used between Cloud Volumes ONTAP and its associated storage accounts. https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-enabling-private-link.html[Learn how Cloud Volumes ONTAP uses an Azure Private Link^]

* Google Cloud
+
If you want to use BlueXP services with Google Cloud, then you must use a Connector that's running in Google Cloud.

* On your premises

== Communication with cloud providers

The Connector uses TLS 1.2 for all communication to AWS, Azure, and Google Cloud.

== Restricted mode and private mode

To use BlueXP in restricted mode or private mode, you get started with BlueXP by installing the Connector and then accessing the user interface that's running locally on the Connector.

link:concept-modes.html[Learn about BlueXP deployment modes].

== How to create a Connector

You can create a Connector directly from BlueXP, from your cloud provider's marketplace, or by manually installing the software on your own Linux host. How you get started depends on whether you're using BlueXP in standard mode, restricted mode, or private mode.

* link:concept-modes.html[Learn about BlueXP deployment modes]
* link:task-quick-start-standard-mode.html[Get started with BlueXP in standard mode]
* link:task-quick-start-restricted-mode.html[Get started with BlueXP in restricted mode]
* link:task-quick-start-private-mode.html[Get started with BlueXP in private mode]

== Permissions

Specific permissions are needed to create the Connector directly from BlueXP and another set of permissions are needed for the Connector instance itself. If you create the Connector in AWS or Azure directly from BlueXP, then BlueXP creates the Connector with the permissions that it needs.

When using BlueXP in standard mode, how you provide permissions depends on how you plan to create the Connector.

To learn how to set up permissions, refer to the following:

* Standard mode
** link:concept-install-options-aws.html[Connector installation options in AWS]
** link:concept-install-options-azure.html[Connector installation options in Azure]
** link:concept-install-options-google.html[Connector installation options in Google Cloud]
** link:task-install-connector-on-prem.html#step-4-set-up-cloud-permissions[Set up cloud permissions for on-prem deployments]
* link:task-prepare-restricted-mode.html#step-6-prepare-cloud-permissions[Set up permissions for restricted mode]
* link:task-prepare-private-mode.html#step-6-prepare-cloud-permissions[Set up permissions for private mode]

To view the exact permissions that the Connector needs for day-to-day operations, refer to the following pages:

* link:reference-permissions-aws.html[Learn how the Connector uses AWS permissions]
* link:reference-permissions-azure.html[Learn how the Connector uses Azure permissions]
* link:reference-permissions-gcp.html[Learn how the Connector uses Google Cloud permissions]

It's your responsibility to update the Connector policies as new permissions are added in subsequent releases. If new permissions are required, they will be listed in the release notes.

== Connector upgrades

NetApp typically updates the Connector software each month to introduce new features and to provide stability improvements. While most of the services and features in the BlueXP platform are offered through SaaS-based software, a few features are dependent on the version of the Connector. That includes Cloud Volumes ONTAP management, on-prem ONTAP cluster management, settings, and help.

When you use BlueXP in standard mode or restricted mode, the Connector automatically updates its software to the latest version, as long as it has outbound internet access to obtain the software update. If you're using BlueXP in private mode, then you'll need to manually upgrade the Connector.

link:task-upgrade-connector.html[Learn how to manually upgrade the Connector software when using private mode].

== Operating system and VM maintenance

include::_include/vm-maintenance.adoc[]

<<Connectors must be operational at all times,Be aware that the Connector must be operational at all times>>.

== Multiple working environments and Connectors

You can use the same Connector to manage multiple working environments in BlueXP. The maximum number of working environments that a single Connector should manage varies. It depends on the type of working environments, the number of volumes, the amount of capacity being managed, and the number of users. 

If you have a large-scale deployment, work with your NetApp representative to size your environment. 

Another consideration when determining how many Connector you need is where your storage resides. For example, if you have Cloud Volumes ONTAP in both Google Cloud and Azure, you'll need a Connector for each environment. In cases where your storage exists entirely on-premises, you can run your Connector in any hyperscaler or on your premises. 

Here are other examples:

* You have a multi-cloud environment (for example, AWS and Azure) and you prefer to have one Connector in AWS and another in Azure. Each manages the Cloud Volumes ONTAP systems running in those environments.

* A service provider might use one BlueXP organization to provide services for their customers, while using another organization to provide disaster recovery for one of their business units. Each organization would have separate Connectors.