---
sidebar: sidebar
permalink: faq-accounts-to-organizations.html
keywords: 
summary: 
---

= Moving from accounts to IAM
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP is introducing a new resource and access management model that provides more granular management of resources and permissions. As a part of this change, we're introducing a new resource hierarchy model. The top-level element in the hierarchy model is now an _organization_. Previously, the top-level entry was an account. Your existing accounts will be migrated to the new resource hierarchy model.

These enhancements provide better control over the actions that users can perform and the resources that they can access. 

* A top-level organization enables you to manage access across your various projects
* For users, the roles that you assign can be scoped to the entire organization or to a specific folder or project

	- New terms
		Account   ---> Organization
		Workspace ---> Project

    - More granular permissions management
		- You can now associate a user with multiple roles, with each role scoped a folder or project

	- More granular resource management
		- You can now use folders to group projects (previously workspaces)
		- You can associate a resource to one or more folders or projects

There's no change to your existing users or working environments. When you log in, you'll notice these changes:

* Your account is now called an organization
* Your workspaces are now called projects
* The names of user roles have changed:
** is now 
** is now
** is now
+
While the names of the roles have changed, there are no differences from a permissions perspective. Users will continue to have access to the same resources as before.