settings:
  name: Setup and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Setup and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Known limitations
          url: /reference-limitations.html
        - title: Changes to supported Linux operating systems
          url: /reference-connector-operating-system-changes.html
    - title: Get started
      entries:
        - title: Learn the basics
          entries: 
            - title: BlueXP
              url: /concept-overview.html
            - title: Accounts
              url: /concept-netapp-accounts.html
            - title: Connectors
              url: /concept-connectors.html
            - title: Deployment modes
              url: /concept-modes.html
        - title: Get started with standard mode
          entries:
            - title: Getting started workflow
              url: /task-quick-start-standard-mode.html
            - title: Prepare networking for using the BlueXP console
              url: /reference-networking-saas-console.html
            - title: Sign up to BlueXP
              url: /task-sign-up-saas.html
            - title: Create a Connector
              entries:
                - title: AWS
                  entries:
                    - title: Connector installation options
                      url: /concept-install-options-aws.html
                    - title: Create a Connector from BlueXP
                      url: /task-install-connector-aws-bluexp.html
                    - title: Create a Connector from the marketplace
                      url: /task-install-connector-aws-marketplace.html
                    - title: Manually install the Connector
                      url: /task-install-connector-aws-manual.html
                - title: Azure
                  entries:
                    - title: Connector installation options
                      url: /concept-install-options-azure.html
                    - title: Create a Connector from BlueXP
                      url: /task-install-connector-azure-bluexp.html
                    - title: Create a Connector from the marketplace
                      url: /task-install-connector-azure-marketplace.html
                    - title: Manually install the Connector
                      url: /task-install-connector-azure-manual.html
                - title: Google Cloud
                  entries:
                    - title: Connector installation options
                      url: /concept-install-options-google.html
                    - title: Create a Connector from BlueXP or gcloud
                      url: /task-install-connector-google-bluexp-gcloud.html
                    - title: Manually install the Connector
                      url: /task-install-connector-google-manual.html
                - title: On premises
                  url: /task-install-connector-on-prem.html
            - title: Subscribe to BlueXP
              url: /task-subscribe-standard-mode.html
            - title: What you can do next
              url: /reference-whats-next.html
        - title: Get started with restricted mode
          entries:
            - title: Getting started workflow
              url: /task-quick-start-restricted-mode.html
            - title: Prepare for deployment
              url: /task-prepare-restricted-mode.html
            - title: Deploy the Connector
              url: /task-install-restricted-mode.html
            - title: Subscribe to BlueXP
              url: /task-subscribe-restricted-mode.html
            - title: What you can do next
              url: /reference-whats-next-restricted-mode.html
        - title: Get started with private mode
          entries:
            - title: Getting started workflow
              url: /task-quick-start-private-mode.html
            - title: Prepare for deployment
              url: /task-prepare-private-mode.html
            - title: Deploy the Connector
              url: /task-install-private-mode.html
            - title: What you can do next
              url: /reference-whats-next-private-mode.html
        - title: Log in to BlueXP
          url: /task-logging-in.html
    - title: Administer BlueXP
      entries:
        - title: Identity and access management
          entries:
            - title: Learn about IAM
              url: /concept-identity-and-access-management.html
            - title: Get started
              url: /task-iam-get-started.html
            - title: Organize your resources with folders and projects
              url: /task-iam-manage-folders-projects.html
            - title: Manage members and their permissions
              url: /task-iam-manage-members-permissions.html
            - title: Manage your resource hierarchy
              url: /task-iam-manage-resources.html
            - title: Switch between projects and organizations
              url: /task-iam-switch-organizations-projects.html
            - title: Rename your organization
              url: /task-iam-rename-organization.html
            - title: Predefined IAM roles
              url: /reference-predefined-roles.html
        - title: Identity federation
          url: /concept-federation.html
        - title: BlueXP accounts
          entries:
            - title: Manage your BlueXP account
              url: /task-managing-netapp-accounts.html
            - title: Monitor operations in your account
              url: /task-monitor-cm-operations.html
            - title: Create another BlueXP account
              url: /task-create-account.html
            - title: User roles
              url: /reference-user-roles.html
        - title: Connectors
          entries:
            - title: Maintain the VM and OS
              url: /task-maintain-connectors.html
            - title: Install an HTTPS certificate for secure access
              url: /task-installing-https-cert.html
            - title: Configure a Connector to use a proxy server
              url: /task-configuring-proxy.html
            - title: Require the use of IMDSv2 on EC2 instances
              url: /task-require-imdsv2.html
            - title: Upgrade a Connector when using private mode
              url: /task-upgrade-connector.html
            - title: Work with multiple Connectors
              url: /task-manage-multiple-connectors.html
            - title: Troubleshoot the Connector
              url: /task-troubleshoot-connector.html
            - title: Uninstall and remove the Connector
              url: /task-uninstall-connector.html
            - title: Default configuration
              url: /reference-connector-default-config.html
        - title: Credentials and subscriptions
          entries:
            - title: AWS
              entries:
                - title: Learn about credentials and permissions
                  url: /concept-accounts-aws.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-aws-accounts.html
            - title: Azure
              entries:
                - title: Learn about credentials and permissions
                  url: /concept-accounts-azure.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-azure-accounts.html
            - title: Google Cloud
              entries:
                - title: Learn about projects and permissions
                  url: /concept-accounts-gcp.html
                - title: Manage credentials and subscriptions
                  url: /task-adding-gcp-accounts.html
            - title: Manage NSS credentials associated with a BlueXP account
              url: /task-adding-nss-accounts.html
            - title: Manage credentials associated with your BlueXP login
              url: /task-manage-user-credentials.html
    - title: Reference
      entries:
        - title: Permissions
          entries:
            - title: Permissions summary
              url: /reference-permissions.html
            - title: AWS permissions for the Connector
              url: /reference-permissions-aws.html
            - title: Azure permissions for the Connector
              url: /reference-permissions-azure.html
            - title: Google Cloud permissions for the Connector
              url: /reference-permissions-gcp.html
        - title: Ports
          entries:
            - title: Connector security group rules in AWS
              url: /reference-ports-aws.html
            - title: Connector security group rules in Azure
              url: /reference-ports-azure.html
            - title: Connector firewall rules in Google Cloud
              url: /reference-ports-gcp.html
            - title: Ports for the on-prem Connector
              url: /reference-ports-on-prem.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: bluexp-family