settings:
  name: Set up and administration
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
  rss_page: "whats-new.html"
sidebar:
  entries:
    - title: Set up and administration docs
      url: /index.html
    - title: Release notes
      entries:
        - title: What's new
          url: /whats-new.html
        - title: Limitations
          url: /reference-limitations.html
    - title: Get started
      entries:
        - title: Learn about BlueXP
          url: /concept-overview.html
        - title: Supported deployment modes
          url: /concept-modes.html
        - title: Getting started checklist
          url: /reference-checklist-cm.html
        - title: Log in to BlueXP
          url: /task-logging-in.html
        - title: Set up a NetApp account
          entries:
            - title: Learn about NetApp accounts
              url: /concept-netapp-accounts.html
            - title: Set up workspaces and users
              url: /task-setting-up-netapp-accounts.html
        - title: Set up a Connector
          entries:
            - title: Learn about Connectors
              url: /concept-connectors.html
            - title: Create a Connector in AWS
              url: /task-creating-connectors-aws.html
            - title: Create a Connector in Azure
              url: /task-creating-connectors-azure.html
            - title: Create a Connector in Google Cloud
              url: /task-creating-connectors-gcp.html
            - title: Create a Connector in a Government region
              url: /task-create-connectors-gov.html
        - title: Where to go next
          url: /reference-whats-next.html
    - title: Administer BlueXP
      entries:
        - title: NetApp accounts
          entries:
            - title: Manage your account
              url: /task-managing-netapp-accounts.html
            - title: Monitor operations in your account
              url: /task-monitor-cm-operations.html
            - title: User roles
              url: /reference-user-roles.html
        - title: Connectors
          entries:
            - title: Advanced deployment
              entries:
                - title: Create from the AWS Marketplace
                  url: /task-launching-aws-mktp.html
                - title: Create from the Azure Marketplace
                  url: /task-launching-azure-mktp.html
                - title: Install on your own host with internet
                  url: /task-installing-linux.html
                - title: Install on-prem without internet
                  url: /task-install-connector-onprem-no-internet.html
            - title: Find the system ID for a Connector
              url: /task-finding-system-id.html
            - title: Manage existing Connectors
              url: /task-managing-connectors.html
            - title: Install an HTTPS certificate
              url: /task-installing-https-cert.html
            - title: Configure proxy settings
              url: /task-configuring-proxy.html
            - title: Default configuration
              url: /reference-connector-default-config.html
        - title: Subscriptions
          url: /task-manage-subscriptions.html
        - title: Discovered cloud storage
          entries:
            - title: View your Amazon S3 buckets
              url: /task-viewing-amazon-s3.html
            - title: View your Azure Blob accounts
              url: /task-viewing-azure-blob.html
            - title: View your Google Cloud Storage buckets
              url: /task-viewing-gcp-storage.html
        - title: AWS credentials
          entries:
            - title: Overview
              url: /concept-accounts-aws.html
            - title: Manage credentials and subscriptions
              url: /task-adding-aws-accounts.html
        - title: Azure credentials
          entries:
            - title: Overview
              url: /concept-accounts-azure.html
            - title: Manage credentials and subscriptions
              url: /task-adding-azure-accounts.html
        - title: Google Cloud credentials
          entries:
            - title: Overview
              url: /concept-accounts-gcp.html
            - title: Manage credentials and subscriptions
              url: /task-adding-gcp-accounts.html
        - title: NetApp Support Site accounts
          url: /task-adding-nss-accounts.html
        - title: Discovery using My Opportunities
          url: /concept-my-opportunities.html
    - title: Reference
      entries:
        - title: Permissions
          entries:
            - title: Permissions summary
              url: /reference-permissions.html
            - title: AWS permissions for the Connector
              url: /reference-permissions-aws.html
            - title: Azure permissions for the Connector
              url: /reference-permissions-azure.html
            - title: Google Cloud permissions for the Connector
              url: /reference-permissions-gcp.html
        - title: Ports
          entries:
            - title: Security group rules in AWS
              url: /reference-ports-aws.html
            - title: Security group rules in Azure
              url: /reference-ports-azure.html
            - title: Firewall rules in Google Cloud
              url: /reference-ports-gcp.html
            - title: Ports for the on-prem Connector
              url: /reference-ports-on-prem.html
    - title: Knowledge and support
      entries:
        - title: Register for support
          url: /task-support-registration.html
        - title: Get help
          url: /task-get-help.html
    - title: Legal notices
      url: /legal-notices.html
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: All BlueXP documentation
homepage:
  tiles:
    - title: Get started
      links:
        - title: Learn about BlueXP
          url: concept-overview.html
        - title: Getting started checklist
          url: reference-checklist-cm.html
    - title: Connectors
      links:
        - title: Learn about Connectors
          url: concept-connectors.html
        - title: Manage Connectors
          url: task-managing-connectors.html
    - title: NetApp accounts
      links:
        - title: Learn about NetApp accounts
          url: concept-netapp-accounts.html
        - title: Set up workspaces and users
          url: task-setting-up-netapp-accounts.html
        - title: Manage your NetApp account
          url: task-managing-netapp-accounts.html
    - title: Cloud provider accounts
      links:
        - title: Manage AWS credentials
          url: task-adding-aws-accounts.html
        - title: Manage Azure credentials
          url: task-adding-azure-accounts.html
        - title: Manage Google Cloud credentials
          url: task-adding-gcp-accounts.html
    - title: Blogs & community
      links:
        - title: NetApp Community
          url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
        - title: BlueXP blog
          url: https://cloud.netapp.com/blog/topic/cloud-manager
        - title: Cloud webinars
          url: https://cloud.netapp.com/events
