---
sidebar: sidebar
permalink: reference-roles.html
keywords: backing up, restoring, back up, backup, restore, cloud volumes ontap, aws, azure, s3, blob, google cloud, storagegrid, back up volumes, cloud backup, restore volumes, cost, on-premises ontap, onprem, applications, virtual machines, backup and recovery, roles, permissions, access control, role-based access control, rbac
summary: BlueXP backup and recovery employs roles to govern the access that each user has to specific features and actions
---

= BlueXP backup and recovery role-based access to features
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP backup and recovery employs roles to govern the access that each user has to specific features and actions. 

The service uses the following roles that are specific to BlueXP backup and recovery. 

* *Backup and recovery super admin*: Perform any actions in BlueXP backup and recovery.
* *Backup admin*: Perform backups to local snapshots, replicate to secondary storage, and back up to object storage actions in BlueXP backup and recovery. 
* *Restore admin*: Restore workloads using BlueXP backup and recovery. 
* *Clone admin*: Clone applications and data using BlueXP backup and recovery. 
* *Backup and recovery viewer*: View information in BlueXP backup and recovery, but not perform any actions.




For details about all BlueXP access roles, see https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[the BlueXP setup and administration documentation^].

The following table indicates the actions that each BlueXP backup and recovery role can perform. 

[cols=6*,options="header",cols="20,20,15,15a,15a,15a",width="100%"]
|===
| Feature and action
| Backup and recovery super admin
| Backup admin
| Restore admin
| Clone admin
| Viewer

|Add, edit, or delete hosts | Yes | No | No | No | No
|Install plugins | Yes | No | No | No | No
|Add credentials (host, instance, vCenter) | Yes | No | No | No | No

| View dashboard and all tabs | Yes | Yes |Yes |Yes | Yes
| Start free trial | Yes | No  |No |No | No
| Initiate discovery of workloads | No | Yes |Yes |Yes | No
| View license information | Yes | Yes |Yes |Yes | Yes
| Activate license | Yes | No  |No |No | No
| View hosts | Yes | Yes |Yes |Yes | Yes

6+| *Schedules*: 
| Activate schedules | Yes | Yes |Yes |Yes | No
| Suspend schedules | Yes | Yes | Yes |Yes | No


6+| *Policies and protection*: 
| View protection plans | Yes | Yes  |Yes |Yes | Yes
| Create, modify, or delete protection | Yes | Yes  |No |No | No
| Restore workloads | Yes | No  |Yes |No | No
| Create clone, split clone, or delete clone | Yes | No  |No |Yes | No
| Create, modify, or delete policy | Yes | Yes  |No |No | No


6+| *Reports*: 
| View reports | Yes | Yes |Yes |Yes | Yes
| Create reports | Yes | Yes |Yes | Yes | No
| Delete reports | Yes | No |No | No | No


6+| *Import from SnapCenter and manage host*: 
| View imported SnapCenter data | Yes | Yes  |Yes |Yes | Yes
| Import data from SnapCenter| Yes | Yes | No | No | No
| Manage (migrate) host| Yes | Yes | No | No | No

6+| *Configure settings*:
| Configure log directory| Yes | Yes  |Yes |No | No
| Associate or remove instance credentials| Yes | Yes |Yes |No | No

6+| *Buckets*:
| View buckets| Yes | Yes  |Yes |Yes | Yes
| Create, edit, or delete bucket| Yes | Yes |No |No | No


|===
