---
sidebar: sidebar
permalink: reference-connector-operating-system-changes.html
keywords: connector, operating systems, connector operating systems, os support, supported operating systems, rhel 8, rhel 9, red hat, docker, podman
summary: As we add and remove support for the Connector on specific Linux operating systems, you might have questions about how this support affects your existing Connector deployments.
---

= Changes to supported Linux operating systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As we add and remove support for the Connector on specific Linux operating systems, you might have questions about how this support affects your existing Connector deployments.

== Supported operating systems

NetApp supports the BlueXP Connector with the following Linux operating systems.

// start tabbed area

[role="tabbed-block"]
====

.Standard mode
--
Manual installation::
* Ubuntu 24.04 LTS
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux 
** 8.6 to 8.10
** 9.1 to 9.4

Deployment from BlueXP::
Ubuntu 22.04 LTS

Deployment from the AWS Marketplace::
Ubuntu 22.04 LTS 

Deployment from the Azure Marketplace::
Ubuntu 22.04 LTS
--

.Restricted mode
--
Manual installation::
* Ubuntu 24.04 LTS
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux
** 8.6 to 8.10
** 9.1 to 9.4

Deployment from the AWS Marketplace::
Ubuntu 22.04 LTS

Deployment from the Azure Marketplace::
Ubuntu 22.04 LTS
--

.Private mode
--
Manual installation::
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux 
** 8.6 to 8.10
** 9.1 to 9.4
--

====

== Support for RHEL 8 and 9

Note the following about support for RHEL 8 and 9:

Limitations::
BlueXP classification is supported if you install the Connector on a RHEL 8 or 9 host that resides on-premises. It's not supported if the RHEL 8 or 9 host resides in AWS, Azure, or Google Cloud.

Container orchestration tool::
You must use the Podman tool as the container orchestration tool when installing the Connector on a RHEL 8 or 9 host. Docker Engine is not supported with RHEL 8 and 9.

Deployment mode::
RHEL 8 and 9 are supported when using BlueXP in standard mode, restricted mode, and private mode.

Supported Connector versions::
NetApp supports RHEL 8 and 9 beginning with the following versions of the Connector:
+
* 3.9.40 when using BlueXP in standard mode or restricted mode
* 3.9.42 when using BlueXP in private mode

New manual installations only::
RHEL 8 and 9 are supported with _new_ Connector installations when manually installing the Connector on hosts running on your premises or in the cloud.

RHEL upgrades::
If you have an existing Connector running on a RHEL 7 host, we don't support upgrading the RHEL 7 operating system to RHEL 8 or 9. <<Existing Connectors on RHEL 7 or CentOS 7,Learn more about existing Connectors on RHEL 7 or CentOS 7>>.

== End of support for RHEL 7 and CentOS 7

On June 30, 2024, RHEL 7 reached end of maintenance (EOM), while CentOS 7 reached end of life (EOL). NetApp stopped supporting the Connector on these Linux distributions on June 30, 2024.

https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance[Red Hat: What to know about Red Hat Enterprise Linux 7 End of Maintenance^]

=== Existing Connectors on RHEL 7 or CentOS 7

If you have an existing Connector running on RHEL 7 or CentOS 7, we don't support upgrading or converting the operating system to RHEL 8 or 9. You need to create a new Connector on a supported operating system.

. Set up a RHEL 8 or 9 host.
. Install Podman.
. Perform a _new_ Connector installation.
. Configure the Connector to discover the working environments that the old Connector was managing.

== Related information

=== How to get started with RHEL 8 and 9

Refer to the following pages for details about host requirements, Podman requirements, and steps to install Podman and the Connector:

// start tabbed area

[role="tabbed-block"]
====

.Standard mode
--
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Install and set up a Connector on-premises]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html[Manually install the Connector in AWS]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html[Manually install the Connector in Azure]
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html[Manually install the Connector in Google Cloud]
--

.Restricted mode
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-restricted-mode.html[Prepare for deployment in restricted mode]
--

.Private mode
--
https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-private-mode.html[Prepare for deployment in private mode]
--

====

=== How to rediscover your working environments

Refer to the following pages to rediscover your working environments after a new Connector deployment.

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html[Add existing Cloud Volumes ONTAP systems to BlueXP^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters^]
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html[Create or discover an FSx for ONTAP working environment^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-working-env.html[Create an Azure NetApp Files working environment^]
* https://docs.netapp.com/us-en/bluexp-e-series/task-discover-e-series.html[Discover E-Series systems^]
* https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html[Discover StorageGRID systems^]