---
sidebar: sidebar
permalink: reference-iam-predefined-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= BlueXP access roles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP identity and access management (IAM) includes several predefined roles that you can assign to the members of your organization across different levels of your resource hierarchy. Before you assign these roles, you should understand the permissions that each role includes. Roles fall into the following categories: platform, application, and data service.

== Platform roles
Platform roles are the broadest roles you can assign to users and allow all permissions forBlueXP administration, including assigning roles and adding users. Users with platform roles have access to all data services and applications within BlueXP. BlueXP IAM includes two platform roles: Organization admin and Folder or Project admin. The main difference between the two BlueXP IAM platform roles is scope. 

=== Organization admin
Allows a user unrestricted access to all projects and folders within an organization, add members to any project or folder, as well as perform any BlueXP task and use any data service.


=== Folder or project admin
Allows a user unrestricted access to specific projects and folders to which they are assigned. Can add members to folders or projects they manage, as well as perform any BlueXP task and use any data service or application on resources within the folder or project they are assigned.


The Folder or Project admin role cannot create Connectors.

=== Platform role comparison table
[cols=5*,options="header",cols="24,19,19"]
|===

| Task
| Organization admin
| Folder or Project admin


| Create Connectors | Yes | No 

| Create, modify or delete working environments (add or discover new resources using the BlueXP canvas) |	Yes | Yes 

| Create folders and projects, including deleting | Yes | No

| Rename existing folders and projects | Yes | Yes 

| Assign roles and add users | Yes | Yes

| Associate resources with folders and projects  | Yes | Yes

| Associate Connectors with folders and projects  | Yes | No

| Remove Connectors from a folders and projects  | Yes | No

| Manage Connectors (edit certificates, settings, and so on)  | Yes | No

| Manage credentials from Settings > Credentials  | Yes | Yes

| View the BlueXP timeline | Yes |	Yes 

| Use BlueXP services | Yes | Yes 

| Register BlueXP for support and submit cases | Yes |	Yes 

|===

Example for organization roles in BlueXP for a large multi-national organization::
XYZ Corporation, a multinational company, aims to segregate access to data storage resources based on geographic regions: North America, Europe, and Asia-Pacific. They want each region to have exclusive control over their resources while maintaining centralized oversight.
+
To achieve this, a person assigned the Organization admin role in XYZ Corporation's BlueXP creates an initial working environment and then creates separate folders in BlueXP for each region. Each region's folder contains projects (with associated resources) related to that region. The Organization admin assigns a BlueXP user in each respective region the Folder/project admin role. 
+
Once the initial setup is complete, regional admins with the Folder or Project admin role can create new working environments and add users within their regions. These regional admins could also add/remove/rename folders and projects to which they are assigned. The Organization admin inherits permissions for any new working environments or resources, maintaining visibility of storage usage across the entire organization.










== Application roles
The following is a list of roles in the application category. Each role grants specific permissions within its designated scope. Users who do not have the required application role or a platform role will be unable to access the application.

=== Keystone roles

You can use the following roles to assign users access to Keystone. 

NOTE: Accessing Keystone through BlueXP is currently in beta. If you would like to participate in the Keystone beta, contact your NetApp representative.

* *Keystone admin*: Manage the Keystone subscription as well as take actions on alerts, reports, and subscriptions.
* *Keystone viewer*: View the Keystone subscription as well as view reports, alerts and assets.

The following table indicates the actions that each Keystone role can perform. 

[cols=3*,options="header",cols="40,20a,20a",width="100%"]
|===
| Feature and action
| Keystone admin
| Keystone viewer

| View the following tabs: Subscription, Assets, Monitor, and Administration | Yes | Yes
3+| *Keystone subscription page*: 
| View subscriptions | Yes | Yes
| Amend or renew subscriptions | Yes | No
3+| *Keystone assets page*: 
| View assets  | Yes | Yes 
| Manage assets | Yes | No
3+| *Keystone alerts page*: 
| View alerts | Yes | No 
| Manage alerts | Yes | No 
| Create alerts for self | Yes | Yes
3+| *Digital wallet*:
| Can view digital wallet | Yes | Yes
3+| *Keystone reports page*:
| Download reports | Yes | Yes
| Manage reports | Yes | Yes
| Create reports for self | Yes | Yes
3+| *Service requests*:
| Create service requests | Yes | No
| CView service requests created by any user within the Organization | Yes | Yes


|===


== Data service roles
The following is a list of roles in the data service category. Each role grants specific permissions within its designated scope. Users who do not have the required data service role or a platform role will be unable to access the data service.


=== Classification viewer

Provides the ability view BlueXP classification scan results.

Classification does not have an admin role.

Permissions::
View compliance information and generate reports for resources that they have permission to access. These users can't enable or disable scanning of volumes, buckets, or database schemas.

No other actions are available to a member who has this role.

=== Ransomware protection

You can use the following roles to assign users access to ransomware protection. 

* *Ransomware protection admin*: Manage actions on the Protect, Alerts, Recover, Settings, and Reports tabs.
* *Ransomware protection viewer*: View workload data, view alert data, download recovery data, and download reports.

The following table indicates that actions that each BlueXP ransomware protection role can perform. 

[cols=3*,options="header",cols="40,20a,20a",width="100%"]
|===
| Feature and action
| Ransomware protection admin
| Ransomware protection viewer

| View dashboard and all tabs | Yes | Yes
| Start free trial | Yes | No 
| Initiate discovery of workloads | Yes | No
3+| *On the Protect tab*: 
| Add, modify, or delete policies | Yes | No
| Protect workloads | Yes | No
| Identify sensitive data| Yes | No 
| Edit workload protection | Yes | No
| View workload details | Yes | Yes 
| Download data| Yes | Yes 
3+| *On the Alerts tab*: 
| View alert details | Yes | Yes 
| Edit incident status | Yes | No
| View incident details | Yes | Yes
| Get full list of impacted files| Yes | No 
| Download alerts data | Yes | Yes 
3+| *On the Recover tab*: 
| Download impacted files| Yes | No 
| Restore workload | Yes | No 
| Download recovery data | Yes | Yes
| Download reports | Yes | Yes
3+| *On the Settings tab*:
| Add or modify backup targets| Yes | No 
| Add or modify SIEM targets | Yes | No
3+| *On the Reports tab*:
| Download reports | Yes | Yes

|===

=== SnapCenter admin

Provides the ability to back up snapshots from on-premises ONTAP clusters using BlueXP backup and recovery for applications.

SnapCenter does not have a viewer role.

Permissions::
A member who has this role can complete the following actions in BlueXP:

* Complete any action from Backup and recovery > Applications
* Manage all working environments in the projects and folders for which they have permissions
* Use all BlueXP services 








== Related links

* link:concept-identity-and-access-management.html[Learn about BlueXP identity and access management]
* link:task-iam-get-started.html[Get started with BlueXP IAM]
* link:task-iam-manage-members-permissions.html[Manage BlueXP members and their permissions]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html[Learn about the API for BlueXP IAM^]