---
sidebar: sidebar
permalink: reference-iam-predefined-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= BlueXP roles and permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP identity and access management (IAM) is designed around a set of roles that you can assign to the members of your organization across different levels of your resource hierarchy.

BlueXP roles are designed to give the least privilege to a user in order for the user to accomplish storage management tasks. This ensures higher security and prevents users from inadvertently disrupting storage services where they do not have permissions.e

== BlueXP IAM administration roles
IAM administration roles are superuser roles that have full permissions for BlueXP administration, including assigning roles and adding users, as well as being able to perform all BlueXP management functions for both storage resources and data services. BlueXP IAM includes two roles: Organization admin and Folder or Project admin. The main difference between these two roles is scope. 


Users must have an IAM role in order to do the following:
* Discover resources
* Create connectors (only Organization admin can create a connector)
* Manage your resource hierarchy (folders and projects)
* Add users and grant roles to users.

=== BlueXP IAM role example for a large multi-national organization
XYZ Corporation, a multinational company, aims to segregate access to data storage resources based on geographic regions: North America, Europe, and Asia-Pacific. They want each region to have exclusive control over their resources while maintaining centralized oversight.

To achieve this, a person assigned the Organization admin role in XYZ Corporation's BlueXP creates an initial working environment and then creates separate folders in BlueXP for each region. Each region's folder contains projects (with associated resources) related to that region. The Organization Admin assigns a BlueXP user in each respective region the Folder/project admin role. 

Once the initial setup is complete, regional admins with the Folder or Project admin role can create new working environments and add users within their regions. These regional admins could also add/remove/rename folders and projects to which they are assigned. The Organization admin inherits permissions for any new working environments or resources, maintaining visibility of storage usage across the entire organization.


=== Organization admin
Allows a user unrestricted access to all projects and folders within an organization, add members to any project or folder, as well as perform any BlueXP task and use any data service.

Only the Organization admin can create Connectors.


=== Folder or project admin
Allows a user unrestricted access to specific projects and folders to which they are assigned.  Can add members to projects or folders they manage, as well as perform any BlueXP task and use any data service within the folder or project they are assigned.


The Folder or Project admin role cannot create Connectors.

=== IAM role comparison table
[cols=5*,options="header",cols="24,19,19"]
|===

| Task
| Organization admin
| Folder or Project admin


| Create connectors | Yes | No 

| Create, modify or delete working environments (add or discover new resources using the BlueXP canvas) |	Yes | Yes 

| Create projects/folders, including deleting | Yes | No

| Rename existing projects/folders | Yes | Yes 

| Assign roles and add users | Yes | Yes

| Associate resources with folders and projects  | Yes | Yes

| Associate connectors with folders and projects  | Yes | No

| Remove connectors from a folders and projects  | Yes | No

| Manage connectors (edit certificates, settings, and so on)  | Yes | No

| Manage credentials from Settings > Credentials  | Yes | Yes

| View the BlueXP timeline | Yes |	Yes 

| Use BlueXP services | Yes | Yes 

| Register BlueXP for support and submit cases | Yes |	Yes 

|===


== Data services roles

BlueXP data services usually have both an admin role and a viewer role. Data services roles are limited in scope to the BlueXP service and the storage resource to which they apply. BlueXP data services usually have both an admin role and a viewer role.

.Admin roles
Admin roles grant permission to perform administrative and management tasks within the scope of the resource and data service to which user is granted the role.

For example, a user within the EMEA project that focuses on data protection can be given administrative roles for the ransomware protection (Ransomware protection admin) and backup and recovery (Backup and recovery admin).

.Viewer roles
Viewer roles are typically assigned to users whose responsibilities include audit and reporting. BlueXP users with this role generally use BlueXP to monitor storage resources and escalate any issues to those responsible for storage management.

A user with a viewer role can view information related to the data service, but generally is not allowed to modify, update or otherwise administer storage within the scope of the respective data service.

For example, a user within the EMEA project that focuses on data protection reporting and auditing can be given viewer roles for both ransomware protection and backup and recovery.

Smaller organizations may choose not to use viewer roles but grant administrative permissions more widely. However, if your organization includes members with audit or reporting duties, consider granting these users a viewer role. 

== SnapCenter admin

Provides the ability to back up snapshots from on-premises ONTAP clusters using BlueXP backup and recovery for applications.

Permissions::
A member who has this role can complete the following actions in BlueXP:
+
* Complete any action from Backup and recovery > Applications
* Manage all working environments in the projects and folders for which they have permissions
* Use all BlueXP services 

== Classification viewer

Provides the ability view BlueXP classification scan results.

Permissions::
View compliance information and generate reports for resources that they have permission to access. These users can't enable or disable scanning of volumes, buckets, or database schemas.
+
No other actions are available to a member who has this role.










== Related links

* link:concept-identity-and-access-management.html[Learn about BlueXP identity and access management]
* link:task-iam-get-started.html[Get started with BlueXP IAM]
* link:task-iam-manage-members-permissions.html[Manage BlueXP members and their permissions]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html[Learn about the API for BlueXP IAM^]