---
sidebar: sidebar
permalink: reference-user-roles.html
keywords: user, users, roles, role, task, permission, permissions, tasks, admin, Account Admin, Workspace Admin, Cloud Compliance Viewer, Cloud Data Sense, SnapCenter Admin
summary: The Account Admin, Workspace Admin, Compliance Viewer, and SnapCenter Admin roles provide specific permissions to users. You can assign one of these roles when you associate a new user with your BlueXP account.
---

= User roles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you use BlueXP in private mode, you'll use a _BlueXP account_ to manage users. You can provide specific permissions to users in your account by selecting from the following roles: Account Admin, Workspace Admin, Compliance Viewer, and SnapCenter Admin.

NOTE: As of February 2025, these user roles are deprecated for standard and restricted deployment modes.  BlueXP private mode only provides one role to associate with users which is the Cloud Manager admin role which grants all BlueXP permissions.

If you're using BlueXP in standard mode or restricted mode, you won't have a BlueXP account. Instead, you'll have a _BlueXP organization_ that you manage using BlueXP identity and access management (IAM).

* link:concept-identity-and-access-management.html[Learn about BlueXP IAM]
* link:concept-modes.html[Learn about BlueXP deployment modes]

[cols=5*,options="header",cols="24,19,19,19,19"]
|===

| Task
| Account Admin
| Workspace Admin
| Compliance Viewer
| SnapCenter Admin

| Create Connectors | Yes | No | No | No

| Manage working environments |	Yes | Yes | No | Yes

| Enable services on working environments | Yes | Yes | No | Yes

| Use BlueXP services | Yes | Yes | No | Yes

| Remove working environments from a workspace | Yes | Yes | No | No

| Delete working environments | Yes | Yes | No | No

| View data replication status | Yes |	Yes | No | No

| View the timeline | Yes |	Yes | No | No

| Switch between workspaces | Yes | Yes | Yes | Yes

| View BlueXP classification scan results | Yes | Yes | Yes | No

| Receive the Cloud Volumes ONTAP report | Yes | No | No | No

| Manage BlueXP accounts | Yes | No | No | No

| Manage credentials | Yes | Yes | No | No

| Modify BlueXP settings |	Yes | Yes | No | No

| View and manage the Support Dashboard | Yes |	Yes | No | No

|===

.Related information

link:task-managing-netapp-accounts.html[Manage your BlueXP account]