---
sidebar: sidebar
permalink: reference-iam-predefined-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= Predefined BlueXP IAM roles and permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP identity and access management (IAM) includes several predefined roles that you can assign to the members of your organization across different levels of your resource hierarchy. Before you assign these roles, you should understand the permissions that each role includes.

== Organization admin

Description::
Provides full control of the entire BlueXP organization. 

Permissions::
A member who has this role can complete all actions in BlueXP.

== Folder or project admin

Description::
Provides full control of one or more projects and folders.
+
Note that if you assign this role at the folder level, the member has permissions to all projects that are associated with that folder.

Permissions::
A member who has this role can complete the following actions in BlueXP:

* Manage all working environments in the projects and folders for which they have permissions
* From BlueXP IAM, manage only the folders and projects for which they have permissions
+
Management actions include associating and dissociating resources, members, and Connectors with the folders and projects.
* Manage credentials
* View the BlueXP timeline
* Register BlueXP for support and submit cases

== Classification viewer

Description::
Provides the ability view BlueXP classification scan results.

Permissions::
View scan results from BlueXP classification without permissions to manage any BlueXP classification settings.
+
No other actions are available to a member who has this role.

== SnapCenter admin

Description::
Provides the ability to back up snapshots from on-premises ONTAP clusters using BlueXP backup and recovery for applications.

Permissions::
Complete any action from Backup and recovery > Applications.
+
No other actions are available to a member who has this role.

== Related links

* link:concept-identity-and-access-management.html[Learn about BlueXP identity and access management]
* link:task-iam-get-started.html[Get started with BlueXP IAM]
* link:task-iam-manage-members-permissions.html[Manage BlueXP members and their permissions]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html[Learn about the API for BlueXP IAM^]