---
sidebar: sidebar
permalink: reference-predefined-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, snapcenter system, role, iam role, admin
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= Predefined BlueXP IAM roles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization. Before you assign these roles, you should understand the permissions that each role includes.

== Organization admin

Description::
Provides full control of the entire BlueXP organization. 

Permissions::
A member who has this role can complete the following actions:

* Manage all working environments
* Manage credentials
* View the BlueXP timeline
* Administer IAM
* Create Connectors
* Register BlueXP for support and submit cases
* Manage alert and notification settings
* Install a CA-signed certificate for web-console access

== Folder or project admin

Description::
Provides full control of one or more projects and folders.

Permissions::
A member who has this role can complete the following actions:

* Manage all working environments in the projects and folders for which you have permissions
* Manage credentials
* View the BlueXP timeline
* Administer IAM by managing the folders and projects for which you have permissions
* Create Connectors?
* Register BlueXP for support and submit cases?

== Classification viewer

Description::
Provides the ability view BlueXP classification scan results without permission to manage BlueXP classification settings.

Permissions::
View BlueXP classification scan results.
+
No other actions are available to a member who has this role.

== SnapCenter admin

Description::
Provides the ability to back up snapshots from on-premises ONTAP clusters.

Permissions::
Back up application-consistent Snapshots from on-premises ONTAP systems using BlueXP backup and recovery for applications.
+
No other actions are available to a member who has this role.

== SnapCenter system

Description::
?

Permissions::
?