---
sidebar: sidebar
permalink: reference-connector-operating-system-changes.html
keywords: connector, operating systems, connector operating systems, os support, supported operating systems, rhel 8, rhel 9, red hat, docker, podman
summary: As we add and remove support for the Connector on specific Linux operating systems, you might have questions about how this support affects your existing Connector deployments.
---

= Changes to supported Linux operating systems
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
As we add and remove support for the Connector on specific Linux operating systems, you might have questions about how this support affects your existing Connector deployments.

== Support for RHEL 8 and 9

BlueXP now supports the Connector with specific versions of Red Hat Enterprise Linux 8 and 9.

Note the following about support for RHEL 8 and 9:

Limitations::
* When the Connector is installed on a RHEL 8 or 9 host, BlueXP backup and recovery has limitations related to single-file restore and ransomware scanning. For details, refer to https://docs.netapp.com/us-en/bluexp-backup-recovery/reference-limitations.html[known limitations for BlueXP backup and recovery^]
* BlueXP classification is supported if you install the Connector on a RHEL 8 or 9 host that resides on-premises. It's not supported if the RHEL 8 or 9 host resides in AWS, Azure, or Google Cloud.

Container orchestration tool::
Podman is required as the container orchestration tool when you install the Connector on a RHEL 8 or 9 host. Docker Engine is not supported with RHEL 8 and 9.
+
link:task-install-connector-on-prem.html#step-1-review-host-requirements[View requirements for Podman].

Deployment mode::
RHEL 8 and 9 are supported when using BlueXP in standard mode or restricted mode.

New manual installations only::
RHEL 8 and 9 are supported with _new_ Connector installations when manually installing the Connector on hosts running on your premises or in the cloud.

RHEL upgrades::
If you have an existing Connector running on a RHEL 7 host, we don't support upgrading the RHEL 7 operating system to RHEL 8 or 9. <<Existing Connectors on RHEL 7 or CentOS 7,Learn more about existing Connectors on RHEL 7 or CentOS 7>>.

== End of support for RHEL 7 and CentOS 7

On June 30, 2024, RHEL 7 reached end of maintenance (EOM), while CentOS 7 reached end of life (EOL). NetApp stopped supporting the Connector on these Linux distributions on June 30, 2024.

https://www.redhat.com/en/technologies/linux-platforms/enterprise-linux/rhel-7-end-of-maintenance[Red Hat: What to know about Red Hat Enterprise Linux 7 End of Maintenance^]

=== Existing Connectors on RHEL 7 or CentOS 7

If you have an existing Connector running on RHEL 7 or CentOS 7, we don't support upgrading or converting the operating system to RHEL 8 or 9. To start running a Connector on a RHEL 8 or 9 host instead, you need to do the following:

. Set up a RHEL 8 or 9 host.
. Install Podman.
. Perform a _new_ Connector installation.
. Configure the Connector to discover the working environments that the old Connector was managing.

== Continued support for Ubuntu 22.04 LTS

The Connector is still supported on Ubuntu 22.04 LTS and is the default operating system for deployments from BlueXP and from the marketplace.

Docker Engine is required for this operating system. Podman is not supported.

== Summary of supported operating systems

Here's a summary of the operating system support that was described in the previous sections.

// start tabbed area

[role="tabbed-block"]
====

.Standard mode
--
Manual installation::
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux 
** 8.6 to 8.10
** 9.1 to 9.3

Deployment from BlueXP:: 
Ubuntu 22.04 LTS

Deployment from the AWS Marketplace:: 
Ubuntu 22.04 LTS 

Deployment from the Azure Marketplace:: 
Ubuntu 22.04 LTS
--

.Restricted mode
--
Manual installation::
* Ubuntu 22.04 LTS
* Red Hat Enterprise Linux
** 8.6 to 8.10
** 9.1 to 9.3

Deployment from the AWS Marketplace:: 
Ubuntu 22.04 LTS

Deployment from the Azure Marketplace:: 
Ubuntu 22.04 LTS
--

.Private mode
--
Manual installation::
Ubuntu 22.04 LTS
--

====

== Related links

=== How to get started with RHEL 8 and 9

Refer to the following pages for details about host requirements, Podman requirements, and steps to install Podman and the Connector:

* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-on-prem.html[Install and set up a Connector on premises] (standard mode)
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-aws-manual.html[Manually install the Connector in AWS] (standard mode)
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-azure-manual.html[Manually install the Connector in Azure] (standard mode)
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-install-connector-google-manual.html[Manually install the Connector in Google Cloud] (standard mode)
* https://docs.netapp.com/us-en/bluexp-setup-admin/task-prepare-restricted-mode.html[Prepare for deployment in restricted mode]

=== How to rediscover your working environments

Refer to the following pages to rediscover your working environments after a new Connector deployment.

* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-adding-systems.html[Add existing Cloud Volumes ONTAP systems to BlueXP^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[Discover on-premises ONTAP clusters^]
* https://docs.netapp.com/us-en/bluexp-fsx-ontap/use/task-creating-fsx-working-environment.html[Create or discover an FSx for ONTAP working environment^]
* https://docs.netapp.com/us-en/bluexp-azure-netapp-files/task-create-working-env.html[Create an Azure NetApp Files working environment^]
* https://docs.netapp.com/us-en/bluexp-e-series/task-discover-e-series.html[Discover E-Series systems^]
* https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html[Discover StorageGRID systems^]