---
sidebar: sidebar
permalink: reference-networking-saas-console.html
keywords: networking, urls, endpoints, web browser, console, network, set up networking
summary: As you use the BlueXP web-based console that's provided through the SaaS layer, it contacts several endpoints when completing a few administrative tasks. Computers that access the BlueXP console should have connections to these endpoints.
---

= Prepare networking for the BlueXP console
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you log in and use the BlueXP web-based console, BlueXP contacts several endpoints to complete the actions that you initiate. Computers that access the BlueXP console must have connections to these endpoints.

These endpoints are contacted in two scenarios:

* From a user's computer when completing specific actions from the https://console.bluexp.netapp.com[BlueXP web-based console^] that's available as software as a service (SaaS).

* If you manually install the Connector, the endpoints are also contacted from a user's computer when opening a web browser, entering the IP address of the Connector host, and then logging in and setting up the Connector.

[cols=2*,options="header,autowidth"]
|===
| Endpoints
| Purpose

| 
\https://console.bluexp.netapp.com
\https://*.console.bluexp.netapp.com

| This is the endpoint that you enter in your web browser to use the BlueXP web-based console.

|
\https://api.bluexp.netapp.com

| The BlueXP web-based console contacts this endpoint to interact with the BlueXP API for actions related to authorization, licensing, subscriptions, credentials, notifications, and more.

| 
\https://aiq.netapp.com

| Required to access BlueXP digital advisor.

a|
AWS services (amazonaws.com):

* CloudFormation
* Elastic Compute Cloud (EC2)
* Key Management Service (KMS)
* Security Token Service (STS)
* Simple Storage Service (S3)

| Required to deploy a Connector from BlueXP in AWS. The exact endpoint depends on the region in which you deploy the Connector. https://docs.aws.amazon.com/general/latest/gr/rande.html[Refer to AWS documentation for details.^]

|
\https://management.azure.com

\https://login.microsoftonline.com

| Required to deploy a Connector from BlueXP in most Azure regions.

|
\https://management.microsoftazure.de

\https://login.microsoftonline.de
| Required to deploy a Connector from BlueXP in Azure Germany regions.

|
\https://management.usgovcloudapi.net

\https://login.microsoftonline.com

| Required to deploy a Connector from BlueXP in Azure US Gov regions.

|
\https://www.googleapis.com

| Required to deploy a Connector from BlueXP in Google Cloud.

| \https://signin.b2c.netapp.com
| Required to update NetApp Support Site (NSS) credentials or to add new NSS credentials to BlueXP.

|
\https://netapp-cloud-account.auth0.com

\https://cdn.auth0.com

\https://services.cloud.netapp.com
| Your web browser connects to these endpoints for centralized user authentication through BlueXP.

| \https://widget.intercom.io
| For in-product chat that enables you to talk to NetApp cloud experts.

|===

Beyond these endpoints, you also need to ensure that the Connector has outbound internet access to contact specific endpoints for day-to-day operations. You can find the list of these endpoints by following the links in the next section below.

.Related information

* Prepare networking for the Connector

** link:task-install-connector-aws-bluexp.html#step-1-set-up-networking[Set up AWS networking]
** link:task-install-connector-azure-bluexp.html#step-1-set-up-networking[Set up Azure networking]
** link:task-install-connector-google-bluexp-gcloud.html#step-1-set-up-networking[Set up Google Cloud networking]
** link:task-install-connector-on-prem.html#step-3-set-up-networking[Set up on-prem networking]

* Prepare networking for BlueXP services
+
Refer to the documentation for each BlueXP service.
+
https://docs.netapp.com/us-en/bluexp-family/[BlueXP documentation^]