---
sidebar: sidebar
permalink: reference-iam-ransomware-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, identity and access management, access roles, admin
summary: BlueXP identity and access management provides two administrative roles that you can assign to the members of your organization.
---

= Ransomware protection access roles for BlueXP
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Ransomware roles provide users access to the Ransomware protection service. Users can be assigned either an administrative role, which allows them to take action in Ransomware protection or a viewer role if they just have monitoring responsibilities. The two roles are Ransomware protection admin and Ransomware protection viewer. The main difference between the two roles is the actions they can take in Ransomware protection.


The following table indicates that actions that each BlueXP ransomware protection role can perform. 

[cols="2,1,1",options="header",cols="40,20a,20a",width="100%"]
|===
| Feature and action
| Ransomware protection admin
| Ransomware protection viewer

| View dashboard and all tabs | Yes | Yes
| Start free trial | Yes | No 
| Initiate discovery of workloads | Yes | No
3+| *On the Protect tab*: 
| Add, modify, or delete policies | Yes | No
| Protect workloads | Yes | No
| Identify sensitive data| Yes | No 
| Edit workload protection | Yes | No
| View workload details | Yes | Yes 
| Download data| Yes | Yes 
3+| *On the Alerts tab*: 
| View alert details | Yes | Yes 
| Edit incident status | Yes | No
| View incident details | Yes | Yes
| Get full list of impacted files| Yes | No 
| Download alerts data | Yes | Yes 
3+| *On the Recover tab*: 
| Download impacted files| Yes | No 
| Restore workload | Yes | No 
| Download recovery data | Yes | Yes
| Download reports | Yes | Yes
3+| *On the Settings tab*:
| Add or modify backup targets| Yes | No 
| Add or modify SIEM targets | Yes | No
3+| *On the Reports tab*:
| Download reports | Yes | Yes

|===

