---
sidebar: sidebar
permalink: reference-iam-predefined-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= Predefined BlueXP IAM roles and permissions
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
BlueXP identity and access management (IAM) includes several predefined roles that you can assign to the members of your organization across different levels of your resource hierarchy. Before you assign these roles, you should understand the permissions that each role includes.

== Administration roles
BlueXP IAM includes two administration roles: Org Admin and Folder/Project admin. The only difference between the two BlueXP IAM admin roles is scope. The Org Admin role can perform these tasks in all folders and projects; while the Folder/project admin can only perform these tasks in the folder or project to which they have been assigned. Both the Org Admin role and the Folder/project Admin roles can do the following:

* Create or modify working environments (add or discover new resources using the BlueXP canvas)
* Create projects/folders, including renaming, removing, and editing
* Create connectors 
* Assign roles and add users
* Use all BlueXP services
* Manage credentials from Settings > Credentials 
* View the BlueXP timeline
* Register BlueXP for support and submit cases


== Data services roles
Data services roles can complete their tasks in any project or folder.


=== SnapCenter admin

Description::
Provides the ability to back up snapshots from on-premises ONTAP clusters using BlueXP backup and recovery for applications.

Permissions::
A member who has this role can complete the following actions in BlueXP:
+
* Complete any action from Backup and recovery > Applications
* Manage all working environments in the projects and folders for which they have permissions
* Use all BlueXP services

=== Classification viewer

Description::
Provides the ability view BlueXP classification scan results.

Permissions::
View compliance information and generate reports for resources that they have permission to access. These users can't enable or disable scanning of volumes, buckets, or database schemas.
+
No other actions are available to a member who has this role.

== Related links

* link:concept-identity-and-access-management.html[Learn about BlueXP identity and access management]
* link:task-iam-get-started.html[Get started with BlueXP IAM]
* link:task-iam-manage-members-permissions.html[Manage BlueXP members and their permissions]
* https://docs.netapp.com/us-en/bluexp-automation/tenancyv4/overview.html[Learn about the API for BlueXP IAM^]