---
sidebar: sidebar
permalink: reference-iam-platform-roles.html
keywords: predefined roles, iam roles, organization admin, folder or project admin, classification viewer, snapcenter admin, role, iam role, admin, iam, identity and access management
summary: BlueXP identity and access management includes several predefined roles that you can assign to the members of your organization.
---

= BlueXP platform access roles
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Platform roles are the broadest roles you can assign to users and allow all permissions forBlueXP administration, including assigning roles and adding users. Users with platform roles have access to all data services and applications within BlueXP. BlueXP includes two platform roles: *Organization admin* and *Folder or Project admin*. The main difference between the two BlueXP platform roles is the scope in which the role applies. 

.Example for organization roles in BlueXP for a large multi-national organization
XYZ Corporation, a multinational company, aims to segregate access to data storage resources based on geographic regions: North America, Europe, and Asia-Pacific. They want each region to have exclusive control over their resources while maintaining centralized oversight.

To achieve this, a person assigned the *Organization admin* role in XYZ Corporation's BlueXP creates an initial working environment and then creates separate folders in BlueXP for each region. Each region's folder contains projects (with associated resources) related to that region. The *Organization admin* assigns a BlueXP user in each respective region the *Folder or project admin* role. 

Once the initial setup is complete, regional admins with the *Folder or project admin* role can create new working environments and add users within their regions. These regional admins could also add/remove/rename folders and projects to which they are assigned. The *Organization admin* inherits permissions for any new working environments or resources, maintaining visibility of storage usage across the entire organization.



The following table indicates the actions that each BlueXP platform role can perform.
[cols="2,1,1",options="header"]
|===

| Task
| Organization admin
| Folder or project admin


| Create Connectors | Yes | No 

| Create, modify or delete working environments (add or discover new resources using the BlueXP canvas) |	Yes | Yes 

| Create folders and projects, including deleting | Yes | No

| Rename existing folders and projects | Yes | Yes 

| Assign roles and add users | Yes | Yes

| Associate resources with folders and projects  | Yes | Yes

| Associate Connectors with folders and projects  | Yes | No

| Remove Connectors from a folders and projects  | Yes | No

| Manage Connectors (edit certificates, settings, and so on)  | Yes | No

| Manage credentials from Settings > Credentials  | Yes | Yes

| View the BlueXP timeline | Yes |	Yes 

| Use BlueXP services | Yes | Yes 

| Register BlueXP for support and submit cases | Yes |	Yes 

|===
