---
sidebar: sidebar
permalink: task-federation-adfs.html
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity
summary: Associate a NetApp Support Site account with your BlueXP organization or account to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire BlueXP organization or account.
---

= Federate BlueXP with Active Directory Federation Services (AD FS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Federate with your Active Directory Federation Services (AD FS) to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.

.Required role
Organization admin. link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. You can't federate with both.

NetApp supports service provider-initiated (SP-initiated) SSO only. You need to first configure the identity provider to trust NetApp as a service provider. Then, you can create a connection in BlueXP that uses the identity provider's configuration.

NOTE: If you want to federate with a domain that is different than your email domain, you must first verify that you own the domain. You can only use verified domains for federation. link:task-federation-verify-domain.html[Learn how to verify your domain.]



== Federate your AD FS with BlueXP
You can set up a federated connection with your AD FS to enable single sign-on (SSO) for BlueXP. The process involves configuring your AD FS to trust NetApp as a service provider and then creating the connection in BlueXP.

.Before you begin
* You must have an IdP server that is accessible from the internet.
* You must have an IdP account with administrative privileges to create the connection. You'll need to work with your IdP administrator to complete these steps.

include::_include/federation-navigation-steps.adoc[]

include::_include/federation-verify-domain-steps.adoc[]


. For your connection method, choose *Protocol* and then select *Active Directory Federation Services (AD FS)*.

. Select *Next*.

. Create a Relying Party Trust in your AD FS server. You can do so through PowerShell or manually in your AD FS server. Consult the AD FS documentation for details on how to create a relying party trust. 
.. Create the trust using PowerShell by using following script:

+
[source, powershell]
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"

.. Alternatively, you can create the trust manually in the AD FS management console. Use the following BlueXP values when creating the trust:

 * When creating the Relying Trust Identifier, use the **YOUR_TENANT** value. For example, `urn:auth0:netapp-cloud-account`
  * When you select *Enable support for the WS-Federation*, use the **YOUR_AUTH0_DOMAIN** value. For example ` https://netapp-cloud-account.auth0.com/login/callback`
 
. After creating the trust, copy the following values from your AD FS server:
.. *Metadata URL*: The URL for the metadata document for the relying party trust. This is typically in the format `https://<your-adfs-server>/FederationMetadata/2007-06/FederationMetadata.xml`.

.Select *Next*.

. Create the connection with AD FS.  
.. Enter the URL of your AD FS server in the *AD FS URL* field. The URL should be in the format `https://<your-adfs-server>/adfs`.
.. Enter the *Metadata URL* that you copied from your AD FS server in the previous step.

. Select *Create connection*.




