---
sidebar: sidebar
permalink: task-federation-entra-id.html
keywords: Microsoft Entra ID, BlueXP, federation, single sign-on, SSO, identity provider, IdP, service provider-initiated SSO, domain verification, client secret, redirect URL, organization admin
summary: Associate a NetApp Support Site account with your BlueXP organization or account to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire BlueXP organization or account.
---

= Federate BlueXP with Microsoft Entra ID
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Federate with your Microsoft Entra ID IdP provider to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.

.Required role
Organization admin. link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. You can't federate with both.

NetApp supports service provider-initiated (SP-initiated) SSO only. You need to first configure the identity provider to trust NetApp as a service provider. Then, you can create a connection in BlueXP that uses the identity provider's configuration.


You can set up a federated connection with Microsoft Entra ID to enable single sign-on (SSO) for BlueXP. The process involves configuring your Microsoft Entra ID to trust NetApp as a service provider and then creating the connection in BlueXP.

include::_include/federation-prereqs.adoc[]



include::_include/federation-navigation-steps.adoc[]

include::_include/federation-verify-domain-steps.adoc[]


. For your connection method, choose *Provider* and then select *Microsoft Entra ID*.

. Select *Next*.

. Configure your Microsoft Entra ID to trust NetApp as a service provider. You need to do this step on your Microsoft Entra ID server.  


.. Use the following values when registering your Microsoft Entra ID app to trust BlueXP: 

+

* For the *Redirect URL* , use `https://services.cloud.netapp.com`
 
* For the *Reply URL*, use `https://netapp-cloud-account.auth0.com/login/callback`


.. Create a client secret for your Microsoft Entra ID app. You'll need to provide the client ID, the client secret, and the Entra ID domain name to complete the federation. 


. Return to BlueXP, and select *Next* to create the connection.

. Create the connection with Microsoft Entra ID  
.. Enter the client ID and Client secret that you created in the previous step.

.. Enter the Microsoft Entra ID domain name. 


. Select *Create connection*. The system creates the connection in a few minutes.

include::_include/federation-test-enable-steps.adoc[]

