---
sidebar: sidebar
permalink: task-create-account.html
keywords: create account, account, create, create another account, tenancy account, tenancy, tenancy account creation
summary: When you set up BlueXP in restricted mode or private mode, you're prompted to create an account. If you need multiple accounts, you need to create them using the Tenancy API.
---

= Create another BlueXP account
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
When you set up BlueXP in restricted mode or private mode, you're prompted to create a _BlueXP account_, which enables you to manage users and organize resources. This account might be all that you need, but if your business requires multiple accounts, then you'll need to create additional accounts by using the Tenancy API.

If you're using BlueXP in standard mode, you won't have a BlueXP account. Instead, you'll have an organization that you manage using BlueXP identity and access management (IAM). link:concept-identity-and-access-management.html[Learn about BlueXP IAM]

.Steps

. Use the following API call to create an additional BlueXP account:
+
POST `/tenancy/account/{accountName}`
+
If you want to enable restricted mode, you need to include the following in the request body:
+
[source,JSON]
{
  "isSaasDisabled": true
}

NOTE: You can't change the restricted mode setting after BlueXP creates the account. You can't enable restricted mode later and you can't disable it later. It must be set at time of account creation.

https://docs.netapp.com/us-en/bluexp-automation/tenancy/post-tenancy-account-id.html[Learn how to use this API call^]

.Related information

* link:concept-netapp-accounts.html[Learn about BlueXP accounts]
* link:concept-modes.html[Learn about BlueXP deployment modes]