---
sidebar: sidebar
permalink: task-federation-adfs.html
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity
summary: Associate a NetApp Support Site account with your BlueXP organization or account to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire BlueXP organization or account.
---

= Federate BlueXP with Active Directory Federation Services (AD FS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Federate with your Active Directory Federation Services (AD FS) to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.

.Required role
Organization admin. link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. You can't federate with both.

NetApp supports service provider-initiated (SP-initiated) SSO only. You need to first configure the identity provider to trust NetApp as a service provider. Then, you can create a connection in BlueXP that uses the identity provider's configuration.





== Federate your AD FS with BlueXP
You can set up a federated connection with your AD FS to enable single sign-on (SSO) for BlueXP. The process involves configuring your AD FS to trust NetApp as a service provider and then creating the connection in BlueXP.

.Before you begin
* You must have an IdP server that is accessible from the internet.
* You must have an IdP account with administrative privileges to create the connection. You'll need to work with your IdP administrator to complete these steps.
* If you want to use a domain other than your email domain, you must first verify the domain in BlueXP. You can do this by following the steps in the link:task-federation-verify-domain.html[Verify your domain in BlueXP] topic.

include::_include/federation-navigation-steps.adoc[]

include::_include/federation-verify-domain-steps.adoc[]


. For your connection method, choose *Protocol* and then select *Active Directory Federation Services (AD FS)*.

. Select *Next*.

. Create a Relying Party Trust in your AD FS server. You can do so through PowerShell or manually in your AD FS server. Consult the AD FS documentation for details on how to create a relying party trust. 

.. Create the trust using PowerShell by using following script:

+
[source, powershell]
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"

.. Alternatively, you can create the trust manually in the AD FS management console. Use the following BlueXP values when creating the trust:

+

* When creating the Relying Trust Identifier, use the **YOUR_TENANT** value. For example, `urn:auth0:netapp-cloud-account`
* When you select *Enable support for the WS-Federation*, use the **YOUR_AUTH0_DOMAIN** value. For example `https://netapp-cloud-account.auth0.com/login/callback`
 
.. After creating the trust, copy the metadata URL from your AD FS server or download the federation metadata file. You'll need this URL or file to complete the connection in BlueXP.

. Return to BlueXP, and select *Next* to create the connection.

. Create the connection with AD FS.  
.. Enter the *AD FS URL* that you copied from your AD FS server in the previous step or uploaded the federation metadata file that you downloaded from your AD FS server.

. Select *Create connection*. Creating the connection might take a few minutes.

. Select *Next* to test the connection. If the test is successful, you can enable the connection.
. Select *Test connection* to enable the connection. You'll be directed to a login page for your AD FS server. Log in with your AD FS credentials to complete the test and then return to BlueXP to enable the connection.





