---
sidebar: sidebar
permalink: task-federation-adfs.html
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity
summary: Associate a NetApp Support Site account with your BlueXP organization or account to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire BlueXP organization or account.
---

= Federate BlueXP with Active Directory Federation Services (AD FS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Federate with your Active Directory Federation Services (AD FS) to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.

.Required role
Organization admin. link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. You can't federate with both.

NetApp supports service provider-initiated (SP-initiated) SSO only. You need to first configure the identity provider to trust NetApp as a service provider. Then, you can create a connection in BlueXP that uses the identity provider's configuration.

NOTE: If you want to federate with a domain that is different than your email domain, you must first verify that you own the domain. You can only use verified domains for federation. link:task-federation-verify-domain.html[Learn how to verify your domain.]



== Federate your AD FS with BlueXP
You can set up a federated connection with your AD FS to enable single sign-on (SSO) for BlueXP. The process involves configuring your AD FS to trust NetApp as a service provider and then creating the connection in BlueXP.

.Before you begin
* You must have an IdP server that is accessible from the internet.
* You must have an IdP account with administrative privileges to create the connection. You'll need to work with your IdP administrator to complete these steps.

include::_include/federation-navigation-steps.adoc[]

include::_include/federation-verify-domain-steps.adoc[]


. For your connection method, choose *Protocol* and then select *Active Directory Federation Services (AD FS)*.

. Select *Next*.

. Configure your AD FS 




