---
sidebar: sidebar
permalink: task-federation-saml.html
keywords: federation, SAML protocol, SAML, federation services,  federate, federated connection, SSO, identity federation, identity management, corporate identity
summary: Associate a NetApp Support Site account with your BlueXP organization or account to enable key workflows for Cloud Volumes ONTAP. These NSS credentials are associated with the entire BlueXP organization or account.
---

= Federate with a SAML identity provider
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
[.lead]
Federate with your SAMP IdP provider to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.

.Required role
Organization admin. link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. You can't federate with both.

NetApp supports service provider-initiated (SP-initiated) SSO only. You need to first configure the identity provider to trust NetApp as a service provider. Then, you can create a connection in BlueXP that uses the identity provider's configuration.





== Federate your SAML provider with BlueXP
You can set up a federated connection with your SAML 2.0 provider to enable single sign-on (SSO) for BlueXP. The process involves configuring your provider to trust NetApp as a service provider and then creating the connection in BlueXP.

.Before you begin
* You must have an IdP server that is accessible from the internet.
* An IdP account with administrative privileges is required to create the connection. Work with your IdP administrator to complete the steps.
* If you want to use a domain other than your email domain, you must first verify the domain in BlueXP. You can do this by following the steps in the link:task-federation-verify-domain.html[Verify your domain in BlueXP] topic.

NetApp supports the following SAML identity providers:
<make a list here>--Tonia

include::_include/federation-navigation-steps.adoc[]

include::_include/federation-verify-domain-steps.adoc[]


. For your connection method, choose *Protocol* and then select *SAML Identity Provider*.

. Select *Next*.

. Configure your SAML identity provider to trust NetApp as a service provider. You need to do this step on your SAML provider server.  

.. Ensure that your IdP has the attribute `email` set to the user's email address. This is required for BlueXP to identify users correctly:
[source, xml]
<saml:AttributeStatement xmlns:x500="urn:oasis:names:tc:SAML:2.0:profiles:attribute:X500" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <saml:Attribute Name="email" NameFormat="urn:oasis:names:tc:SAML:1.1:nameid-format:X509SubjectName">
        <saml:AttributeValue xsi:type="xs:string">email@domain.com</saml:AttributeValue>
    </saml:Attribute>
</saml:AttributeStatement>



.. Use the following values when registering your SAML application with BlueXP: manually in the AD FS management console. Use the following BlueXP values when creating the trust:

+

* For the *Reply URL* or *Assertion Consumer Service (ACS) URL*, use `https://netapp-cloud-account.auth0.com/login/callback`
 
* For the *Logout URL*, use `https://netapp-cloud-account.auth0.com/logout`
* For *Audience/Entity ID*, use `urn:auth0:netapp-cloud-account:<fed-domain-name-saml>` where <fed-domain-name-saml> is the domain name you want to use for federation. For example, if your domain is `example.com`, the Audience/Entity ID would be `urn:auth0:netapp-cloud-account:example.com`.

.. After creating the trust, copy the following values from your SAML provider server:
+   
* Sign In URL
* Sign Out URL (optional)

.. Download the X.509 certificate from your SAML provider server. It needs to be in PEM, CER, or PFX format.


. Return to BlueXP, and select *Next* to create the connection.

. Create the connection with AD FS.  
.. Enter the *Sign In URL* of your SAML server.

.. Upload the X.509 certificate that you downloaded from your SAML provider server. 

.. Optionally, enter the *Sign Out URL* of your SAML server.

. Select *Create connection*. The system creates the connection in a few minutes.

. Select *Next* to test the connection. If the test is successful, you can enable the connection.
.. Select *Test connection* to enable the connection. You'll be directed to a login page for your AD FS server. Log in with your AD FS credentials to complete the test and then return to BlueXP to enable the connection.

. Select *Next*.

. On the *Enable federation* page, do the following:
.. Set a notification window for BlueXP use when it notifies you if connection is about to expire. The notification window is set in days, and the default value is 30 days. You can change this value if needed.
.. If your connection did not automatically set an expiration date, you can pick a date when you want BlueXP to notify you that the connection is about to expire. Use the calendar icon to select a date.
.. Review the federation details and then select *Enable connection*.