---
sidebar: sidebar
permalink: task-federation-adfs.html
keywords: federation, active directory federation services, adfs, ad fs, single sign-on, microsoft, federate, federated connection, SSO, identity federation, identity management, corporate identity
summary: Federate with your Active Directory Federation Services (AD FS) to enable single sign-on (SSO) for BlueXP. This allows users to log in using their corporate credentials.
---

= Federate BlueXP with Active Directory Federation Services (AD FS)
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Federate your Active Directory Federation Services (AD FS) with BlueXP to enable single sign-on (SSO) for BlueXP. This allows users to log in to BlueXP using their corporate credentials.

.Required roles
Organization admin or Federation admin is required to make create and manage federations. Federation viewer can view the Federation page.  link:reference-iam-predefined-roles.html[Learn more about access roles.]

NOTE: You can federate with your corporate IdP or with the NetApp Support Site. NetApp recommends choosing one or the other, but not both.


NetApp supports service provider-initiated (SP-initiated) SSO only. First, configure the identity provider to trust BlueXP as a service provider. Then, create a connection in BlueXP using your identity provider's configuration.


You can set up federation with your AD FS  server to enable single sign-on (SSO) for BlueXP. The process involves configuring your AD FS to trust BlueXP as a service provider and then creating the connection in BlueXP.

include::_include/federation-prereqs.adoc[]

include::_include/federation-navigation-steps.adoc[]




include::_include/federation-verify-domain-steps.adoc[]






. For your connection method, choose *Protocol* and then select *Active Directory Federation Services (AD FS)*.

. Select *Next*.



. Create a Relying Party Trust in your AD FS server. You can use PowerShell or manually configure it on your AD FS server. Consult the AD FS documentation for details on how to create a relying party trust. 

.. Create the trust using PowerShell by using following script:

+
[source, powershell]
(new-object Net.WebClient -property @{Encoding = [Text.Encoding]::UTF8}).DownloadString("https://raw.github.com/auth0/AD FS-auth0/master/AD FS.ps1") | iex
AddRelyingParty "urn:auth0:netapp-cloud-account" "https://netapp-cloud-account.auth0.com/login/callback"

.. Alternatively, you can create the trust manually in the AD FS management console. Use the following BlueXP values when creating the trust:

+

* When creating the Relying Trust Identifier, use the **YOUR_TENANT** value: `netapp-cloud-account`
* When you select *Enable support for the WS-Federation*, use the **YOUR_AUTH0_DOMAIN** value:  `netapp-cloud-account.auth0.com`
 
.. After creating the trust, copy the metadata URL from your AD FS server or download the federation metadata file. You'll need this URL or file to complete the connection in BlueXP.

+ 

NetApp recommends using the metadata URL to let BlueXP automatically retrieve the latest AD FS configuration. If you download the federation metadata file, you will need to update it manually in BlueXP whenever there are changes to your AD FS configuration.

. Return to BlueXP, and select *Next* to create the connection.



. Create the connection with AD FS.  
.. Enter the *AD FS URL* that you copied from your AD FS server in the previous step or upload the federation metadata file that you downloaded from your AD FS server.

. Select *Create connection*. Creating the connection might take a few seconds.



include::_include/federation-test-enable-steps.adoc[]





