---
sidebar: sidebar
permalink: task-install-connector-on-prem.html
keywords: install connector, on prem connector installation, on prem connector, install connector on prem, manual install
summary: Install a Connector on-premises and then log in and set it up to work with your BlueXP organization.
---

= Install and set up a Connector on-premises
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
You can install a Connector on one of your on-premises machines. To run the Connector on-premises, you need to review host requirements, set up your networking, prepare cloud permissions, install the Connector, set up the Connector, and then provide the permissions that you prepared.

.Before you begin

* Review information about link:concept-connectors.html[Connectors].
* You should review link:reference-limitations.html[Connector limitations].

== Step 1: Review host requirements

Run the Connector software on a host that meets operating system, RAM, and port requirements. Ensure that your host meets these requirements before you install the Connector.

include::_include/os-reqs.adoc[tag=manual-uid-range]

include::_include/os-reqs.adoc[tag=dedicated]

include::_include/os-reqs.adoc[tag=hypervisor]

include::_include/os-reqs.adoc[tag=os]


include::_include/os-reqs.adoc[tag=disk-space]

[[podman-configuration]]
== Step 2: Install Podman or Docker Engine

include::_include/podman-docker.adoc[]

== Step 3: Set up networking

Set up networking to ensure the Connector can manage resources, with connections to target networks and outbound internet access.

//Connections to target networks
include::_include/networking.adoc[tag=networks]

//Outbound internet access
include::_include/networking.adoc[tag=outbound]

//Endpoints contacted from your web browser
include::_include/endpoints-console.adoc[]

//Endpoints contacted during manual installation
include::_include/endpoints-manual-install.adoc[tag=endpoint-list]
include::_include/endpoints-manual-install.adoc[tag=endpoint-list-images-explanation]

+
include::_include/endpoints-manual-install.adoc[tag=update]

//Endpoints contacted from the Connector 
include::_include/endpoints-connector.adoc[tag=intro]
+
[cols="2a,1a",options="header,autowidth"]
|===
| Endpoints
| Purpose

include::_include/endpoints-connector.adoc[tag=aws-endpoints]

include::_include/endpoints-connector.adoc[tag=azure-public-endpoints]

include::_include/endpoints-connector.adoc[tag=azure-china-endpoints]

include::_include/endpoints-connector.adoc[tag=google-cloud-endpoints]

include::_include/endpoints-connector.adoc[tag=nss-endpoints]

include::_include/endpoints-connector.adoc[tag=saas-endpoints]

include::_include/endpoints-connector.adoc[tag=upgrade-endpoints]

|===
+
//Notes about the upgrade endpoints
include::_include/endpoints-connector.adoc[tag=upgrade-endpoints-explanation]

//Proxy server
include::_include/networking.adoc[tag=proxy]

//Ports
include::_include/networking.adoc[tag=ports]

//NTP
include::_include/networking.adoc[tag=ntp]

== Step 4: Set up cloud permissions

If you want to use BlueXP services in AWS or Azure with an on-premises Connector, then you need to set up permissions in your cloud provider so that you can add the credentials to the Connector after you install it.

TIP: Why not Google Cloud? When the Connector is installed on your premises, it can't manage your resources in Google Cloud. You must install the Connector in Google Cloud to manage any resources that reside there.

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
When the Connector is installed on-premises, you need to provide BlueXP with AWS permissions by adding access keys for an IAM user who has the required permissions. 

You must use this authentication method if the Connector is installed on-premises. You can't use an IAM role.

.Steps

include::_include/aws-permissions.adoc[tag=policy]
+
Depending on the BlueXP services that you're planning to use, you might need to create a second policy.
+
For standard regions, the permissions are spread across two policies. Two policies are required due to a maximum character size limit for managed policies in AWS. link:reference-permissions-aws.html[Learn more about IAM policies for the Connector].

include::_include/aws-permissions.adoc[tag=keys]

.Result

You should now have access keys for an IAM user who has the required permissions. After you install the Connector, associate these credentials with the Connector from BlueXP.
--

.Azure
--
When the Connector is installed on-premises, you need to provide BlueXP with Azure permissions by setting up a service principal in Microsoft Entra ID and obtaining the Azure credentials that BlueXP needs.

.Create a Microsoft Entra application for role-based access control

include::_include/azure-set-up-service-principal.adoc[tag=app]

.Assign the application to a role
 
include::_include/azure-set-up-service-principal.adoc[tag=role]

.Add Windows Azure Service Management API permissions

include::_include/azure-set-up-service-principal.adoc[tag=api]

.Get the application ID and directory ID for the application

include::_include/azure-set-up-service-principal.adoc[tag=ids]

.Create a client secret

include::_include/azure-set-up-service-principal.adoc[tags=secret]

--

====
// end tabbed area

== Step 5: Install the Connector

Download and install the Connector software on an existing Linux host on-premises.

include::_include/manual-install.adoc[tag=before]

include::_include/manual-install.adoc[tag=about]

include::_include/manual-install.adoc[tag=main-steps]

.Result

At the end of the installation, the Connector service (occm) restarts twice if you specified a proxy server.

== Step 6: Register the Connector with BlueXP

Log into BlueXP and associate the Connector with your organization. How you log in depends on the mode in which you are using BlueXP. If you are using BlueXP in standard mode, you log in through the SaaS website. If you are using BlueXP in restricted or private mode, you log in locally from the Connector host.

.Steps


. Open a web browser and enter the following URL:
+
https://_ipaddress_
+
_ipaddress_ can be localhost, a private IP address, or a public IP address, depending on the configuration of the host. For example, if the Connector is in the public cloud without a public IP address, you must enter a private IP address from a host that has a connection to the Connector host.

. Sign up or log in.

. After you log in, set up BlueXP:
.. Specify the BlueXP organization to associate with the Connector.
.. Enter a name for the system.
.. Under *Are you running in a secured environment?* keep restricted mode disabled.
+
Keep restricted mode disabled because these steps use BlueXP in standard mode. (In addition, restricted mode isn't supported when the Connector is installed on-premises.)
.. Select *Let's start*.



== Step 7: Provide permissions to BlueXP

After you install and set up the Connector, add your cloud credentials so that BlueXP has the required permissions to perform actions in AWS or Azure.

// start tabbed area

[role="tabbed-block"]
====

.AWS
--
.Before you begin

If you just created these AWS credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials to BlueXP.

.Steps

include::_include/provide-permissions-access-key.adoc[]

You can now go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

.Azure
--

.Before you begin

If you just created these Azure credentials, they may take a few minutes to become available. Wait a few minutes before you add the credentials to BlueXP.

.Steps

include::_include/azure-provide-permissions-service-principal.adoc[]

.Result

BlueXP now has the permissions that it needs to perform actions in Azure on your behalf. You can now go to the https://console.bluexp.netapp.com[BlueXP console^] to start using the Connector with BlueXP.
--

====

// end tabbed area