=== Connector 3.9.53

This release of the BlueXP Connector includes security improvements and bug fixes. 

The 3.9.53 release is available for standard mode and restricted mode.

=== Disk space usage alerts
The Notifications Center now includes alerts for disk space usage on the Connector. link:task-maintain-connectors.html#monitor-disk-space[Learn more.^]

=== Audit improvements
The Timeline now includes login events for users. This enables you to see when users logged in to BlueXP, which can help with auditing and security monitoring. API users who have the Organization administrator role can view the email address of the user who logged in by including the `includeUserData=true`` parameter as in the following: `/audit/<account_id>?includeUserData=true`.






<<<<<<< keystone-test

=======
>>>>>>> main
=== Keystone subscription management available in BlueXP

You can manage your NetApp Keystone subscription from BlueXP.

link:https://docs.netapp.com/us-en/keystone-staas/index.html[Learn about Keystone subscription management in BlueXP.^]


=== BlueXP Identity and Access Management (IAM)

==== Multi-factor authentication (MFA)

Unfederated users can now enable multi-factor authentication (MFA) for their BlueXP accounts, enhancing account security. BlueXP administrators can manage MFA settings for their users, resetting or disabling MFA for individual users as needed. This is supported in standard mode only.

link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-user-settings.html#task-user-mfa[Learn about setting up multi-factor authentication for yourself.^]
link:https://docs.netapp.com/us-en/bluexp-setup-admin/task-iam-manage-members-permissions.html#manage-mfa[Learn about administering multi-factor authentication for users.^]


=== Workloads
You can now view and delete Amazon FSx for NetApp ONTAP credentials from the Credentials page in BlueXP. 








