=== Connector 3.9.54

This release of the BlueXP Connector includes security improvements, bug fixes, and the following new features: 

* Support for transparent proxies for Connectors dedicated to supporting Cloud Volumes ONTAP services. link:https://docs.netapp.com/us-en/bluexp/task-configuring-proxy.html[Learn more about configuring a transparent proxy.]

* Ability to use network tags to help route Connector traffic when the Connector is deployed in a Google Cloud environment.

* Additional alerts for Connector health monitoring, including CPU and RAM usage.

At this time, the 3.9.54 release is available for standard mode and restricted mode.




=== BlueXP Identity and Access Management (IAM)

==== Streamlined management of identity federations

BlueXP now offers a more intuitive interface for managing identity federation. This includes easier navigation, clearer options for configuring federated connections, and improved visibility into existing federations.

Enabling single sign-on (SSO) through identity federation lets users log in to BlueXP and NetApp services with corporate credentials. This boosts security, reduces password fatigue, and simplifies onboarding.

You'll be prompted to import any existing federated connections to the new interface to gain access to the new management features. This allows you to take advantage of the latest enhancements without having to recreate your federated connections. link:https://docs.netapp.com/us-en/bluexp/task-federation-import.html[Learn more about importing your existing federated connection to BlueXP.]

Improved federation management allows you to:

* Add more than one verified domain to a federated connection, allowing you to use multiple domains with the same identity provider (IdP).

* Configure notifications for expiring federated connections, ensuring that you stay informed about the status of your federations.

* Disable or delete federated connections when needed, giving you control over user access and security.

link:https://docs.netap.com/us-en/bluexp-setup-admin/concept-federation.html[Learn more about identity federation in BlueXP.]


==== Support for IAM roles for BlueXP backup and recover and BlueXP disaster recovery

BlueXP now supports using IAM roles for BlueXP backup and recover and BlueXP disaster recovery. This allows you to manage permissions more effectively and securely, ensuring that only authorized users can perform operations for these services.

link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html[Learn more about using IAM roles for BlueXP backup and recover and BlueXP disaster recovery.]













