=== Connector 3.9.52

This release of the BlueXP Connector includes minor security improvements and bug fixes, as well as some additional updates.

=== Updated Azure permissions

We updated Azure policies for the Connector to add permissions that are required for Cloud Volumes ONTAP version 9.15.1C1 and above. 

* https://docs.netapp.com/us-en/bluexp-setup-admin/reference-permissions-azure.html#change-log[Learn what changed in the Azure policy].




At this time, the 3.9.52 release is available for standard mode and restricted mode.

=== Keystone available in BlueXP

You can now access Keystone services directly from BlueXP. This integration allows you to manage subscriptions, monitor usage, and optimize costs seamlessly within the BlueXP interface.




=== BlueXP Identity and Access Management (IAM)

The Storage admin and Storage viewer roles are available and can be assigned to users.


* Storage admin:

* Storage viewer: 

+

link:https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html[Learn about access roles.^]

* If you have the Org admin or Folder or project admin role, you can now associate a Keystone subscription with an IAM project. Associating a Keystone subscription with an IAM project allows you to control access to Keystone within BlueXP.





