










=== BlueXP Identity and Access Management (IAM)

==== Streamlined management of identity federations

BlueXP now offers a more intuitive interface for managing identity federation. This includes easier navigation, clearer options for configuring federated connections, and improved visibility into existing federations.

Enabling single sign-on (SSO) through identity federation lets users log in to BlueXP and NetApp services with corporate credentials. This boosts security, reduces password fatigue, and simplifies onboarding.

You are prompted to import existing federated connections to access new management features. This allows you to use the latest enhancements without having to recreate your federated connections.link:https://docs.netapp.com/us-en/bluexp/task-federation-import.html[Learn more about importing your existing federated connection to BlueXP.]

Improved federation management allows you to:

* Add more than one verified domain to a federated connection, allowing you to use multiple domains with the same identity provider (IdP).

* Configure notifications for expiring federated connections, ensuring that you stay informed about the status of your federations.

* Disable or delete federated connections when needed, giving you control over user access and security.

* Use BlueXP access roles to control which users can create, manage, or view federations. This ensures that only authorized users can make changes to federated connections.

link:https://docs.netap.com/us-en/bluexp-setup-admin/concept-federation.html[Learn more about identity federation in BlueXP.]














