Depending on your operating system, either Podman or Docker Engine is required before you install the Connector.

* Podman is required for Red Hat Enterprise Linux 8.8 and 9.3.

* Docker Engine is required for Ubuntu, CentOS, and Red Hat Enterprise Linux 7.x.

.Steps

[role="tabbed-block"]
====
.Podman
--
Install Podman 4.6.1 or later.

.Steps

. Install Podman.
+
Podman is available from official Red Hat Enterprise Linux repositories. You can install podman by using the `yum` or `dnf` commands. The install command installs the latest version available from the repo.
+
[source,cli]
sudo dnf install podman

. Enable and start the podman.socket service.
+
[source,cli]
sudo systemctl enable --now podman.socket

. Install python3.
+
[source,cli]
sudo dnf install python3

. Install pip3.
+
In most cases, installing python3 will automatically install pip3. If it's not installed, use the following command.
+
[source,cli]
sudo dnf install python3-pip

. Install the podman-compose package 1.0.6 or later.
+
podman-compose is available from the Extra Packages for Enterprise Linux (EPEL) repository. The install command installs the latest version available from the repo.
+
[source,cli]
sudo dnf install podman-compose

+
TIP: Using the `dnf` command adds podman-compose to /usr/bin, which is already included in the `secure_path` option on the host. If you install podman-compose using `pip3`, then you must manually add the podman-compose path to the `secure_path` option in the /etc/sudoers file.

--

.Docker Engine
--
Install Docker Engine 19.3.1 or later.

.Steps

. Install Docker Engine.
+
https://docs.docker.com/engine/install/[View installation instructions from Docker^]

. Verify that Docker is enabled and running.
+
[source,cli]
sudo systemctl enable docker && sudo systemctl start docker
--

====
// end tabbed area